//
// kiwakiwaaにより 2026/03/07 に作成されました。
//

#pragma once

#include <cstdint>
#include <utility>

namespace MKD::detail::unicode::data
{
    /*
     * Case mapping pairs for Unicode characters
     */
    inline constexpr std::pair<char32_t, char32_t> kCasePairs[] = {
        {U'A', U'a'}, // LATIN CAPITAL LETTER A / LATIN SMALL LETTER A
        {U'B', U'b'}, // LATIN CAPITAL LETTER B / LATIN SMALL LETTER B
        {U'C', U'c'}, // LATIN CAPITAL LETTER C / LATIN SMALL LETTER C
        {U'D', U'd'}, // LATIN CAPITAL LETTER D / LATIN SMALL LETTER D
        {U'E', U'e'}, // LATIN CAPITAL LETTER E / LATIN SMALL LETTER E
        {U'F', U'f'}, // LATIN CAPITAL LETTER F / LATIN SMALL LETTER F
        {U'G', U'g'}, // LATIN CAPITAL LETTER G / LATIN SMALL LETTER G
        {U'H', U'h'}, // LATIN CAPITAL LETTER H / LATIN SMALL LETTER H
        {U'I', U'i'}, // LATIN CAPITAL LETTER I / LATIN SMALL LETTER I
        {U'J', U'j'}, // LATIN CAPITAL LETTER J / LATIN SMALL LETTER J
        {U'K', U'k'}, // LATIN CAPITAL LETTER K / LATIN SMALL LETTER K
        {U'L', U'l'}, // LATIN CAPITAL LETTER L / LATIN SMALL LETTER L
        {U'M', U'm'}, // LATIN CAPITAL LETTER M / LATIN SMALL LETTER M
        {U'N', U'n'}, // LATIN CAPITAL LETTER N / LATIN SMALL LETTER N
        {U'O', U'o'}, // LATIN CAPITAL LETTER O / LATIN SMALL LETTER O
        {U'P', U'p'}, // LATIN CAPITAL LETTER P / LATIN SMALL LETTER P
        {U'Q', U'q'}, // LATIN CAPITAL LETTER Q / LATIN SMALL LETTER Q
        {U'R', U'r'}, // LATIN CAPITAL LETTER R / LATIN SMALL LETTER R
        {U'S', U's'}, // LATIN CAPITAL LETTER S / LATIN SMALL LETTER S
        {U'T', U't'}, // LATIN CAPITAL LETTER T / LATIN SMALL LETTER T
        {U'U', U'u'}, // LATIN CAPITAL LETTER U / LATIN SMALL LETTER U
        {U'V', U'v'}, // LATIN CAPITAL LETTER V / LATIN SMALL LETTER V
        {U'W', U'w'}, // LATIN CAPITAL LETTER W / LATIN SMALL LETTER W
        {U'X', U'x'}, // LATIN CAPITAL LETTER X / LATIN SMALL LETTER X
        {U'Y', U'y'}, // LATIN CAPITAL LETTER Y / LATIN SMALL LETTER Y
        {U'Z', U'z'}, // LATIN CAPITAL LETTER Z / LATIN SMALL LETTER Z
        {U'À', U'à'}, // LATIN CAPITAL LETTER A WITH GRAVE / LATIN SMALL LETTER A WITH GRAVE
        {U'Á', U'á'}, // LATIN CAPITAL LETTER A WITH ACUTE / LATIN SMALL LETTER A WITH ACUTE
        {U'Â', U'â'}, // LATIN CAPITAL LETTER A WITH CIRCUMFLEX / LATIN SMALL LETTER A WITH CIRCUMFLEX
        {U'Ã', U'ã'}, // LATIN CAPITAL LETTER A WITH TILDE / LATIN SMALL LETTER A WITH TILDE
        {U'Ä', U'ä'}, // LATIN CAPITAL LETTER A WITH DIAERESIS / LATIN SMALL LETTER A WITH DIAERESIS
        {U'Å', U'å'}, // LATIN CAPITAL LETTER A WITH RING ABOVE / LATIN SMALL LETTER A WITH RING ABOVE
        {U'Æ', U'æ'}, // LATIN CAPITAL LETTER AE / LATIN SMALL LETTER AE
        {U'Ç', U'ç'}, // LATIN CAPITAL LETTER C WITH CEDILLA / LATIN SMALL LETTER C WITH CEDILLA
        {U'È', U'è'}, // LATIN CAPITAL LETTER E WITH GRAVE / LATIN SMALL LETTER E WITH GRAVE
        {U'É', U'é'}, // LATIN CAPITAL LETTER E WITH ACUTE / LATIN SMALL LETTER E WITH ACUTE
        {U'Ê', U'ê'}, // LATIN CAPITAL LETTER E WITH CIRCUMFLEX / LATIN SMALL LETTER E WITH CIRCUMFLEX
        {U'Ë', U'ë'}, // LATIN CAPITAL LETTER E WITH DIAERESIS / LATIN SMALL LETTER E WITH DIAERESIS
        {U'Ì', U'ì'}, // LATIN CAPITAL LETTER I WITH GRAVE / LATIN SMALL LETTER I WITH GRAVE
        {U'Í', U'í'}, // LATIN CAPITAL LETTER I WITH ACUTE / LATIN SMALL LETTER I WITH ACUTE
        {U'Î', U'î'}, // LATIN CAPITAL LETTER I WITH CIRCUMFLEX / LATIN SMALL LETTER I WITH CIRCUMFLEX
        {U'Ï', U'ï'}, // LATIN CAPITAL LETTER I WITH DIAERESIS / LATIN SMALL LETTER I WITH DIAERESIS
        {U'Ð', U'ð'}, // LATIN CAPITAL LETTER ETH / LATIN SMALL LETTER ETH
        {U'Ñ', U'ñ'}, // LATIN CAPITAL LETTER N WITH TILDE / LATIN SMALL LETTER N WITH TILDE
        {U'Ò', U'ò'}, // LATIN CAPITAL LETTER O WITH GRAVE / LATIN SMALL LETTER O WITH GRAVE
        {U'Ó', U'ó'}, // LATIN CAPITAL LETTER O WITH ACUTE / LATIN SMALL LETTER O WITH ACUTE
        {U'Ô', U'ô'}, // LATIN CAPITAL LETTER O WITH CIRCUMFLEX / LATIN SMALL LETTER O WITH CIRCUMFLEX
        {U'Õ', U'õ'}, // LATIN CAPITAL LETTER O WITH TILDE / LATIN SMALL LETTER O WITH TILDE
        {U'Ö', U'ö'}, // LATIN CAPITAL LETTER O WITH DIAERESIS / LATIN SMALL LETTER O WITH DIAERESIS
        {U'Ø', U'ø'}, // LATIN CAPITAL LETTER O WITH STROKE / LATIN SMALL LETTER O WITH STROKE
        {U'Ù', U'ù'}, // LATIN CAPITAL LETTER U WITH GRAVE / LATIN SMALL LETTER U WITH GRAVE
        {U'Ú', U'ú'}, // LATIN CAPITAL LETTER U WITH ACUTE / LATIN SMALL LETTER U WITH ACUTE
        {U'Û', U'û'}, // LATIN CAPITAL LETTER U WITH CIRCUMFLEX / LATIN SMALL LETTER U WITH CIRCUMFLEX
        {U'Ü', U'ü'}, // LATIN CAPITAL LETTER U WITH DIAERESIS / LATIN SMALL LETTER U WITH DIAERESIS
        {U'Ý', U'ý'}, // LATIN CAPITAL LETTER Y WITH ACUTE / LATIN SMALL LETTER Y WITH ACUTE
        {U'Þ', U'þ'}, // LATIN CAPITAL LETTER THORN / LATIN SMALL LETTER THORN
        {U'Ā', U'ā'}, // LATIN CAPITAL LETTER A WITH MACRON / LATIN SMALL LETTER A WITH MACRON
        {U'Ă', U'ă'}, // LATIN CAPITAL LETTER A WITH BREVE / LATIN SMALL LETTER A WITH BREVE
        {U'Ą', U'ą'}, // LATIN CAPITAL LETTER A WITH OGONEK / LATIN SMALL LETTER A WITH OGONEK
        {U'Ć', U'ć'}, // LATIN CAPITAL LETTER C WITH ACUTE / LATIN SMALL LETTER C WITH ACUTE
        {U'Ĉ', U'ĉ'}, // LATIN CAPITAL LETTER C WITH CIRCUMFLEX / LATIN SMALL LETTER C WITH CIRCUMFLEX
        {U'Ċ', U'ċ'}, // LATIN CAPITAL LETTER C WITH DOT ABOVE / LATIN SMALL LETTER C WITH DOT ABOVE
        {U'Č', U'č'}, // LATIN CAPITAL LETTER C WITH CARON / LATIN SMALL LETTER C WITH CARON
        {U'Ď', U'ď'}, // LATIN CAPITAL LETTER D WITH CARON / LATIN SMALL LETTER D WITH CARON
        {U'Đ', U'đ'}, // LATIN CAPITAL LETTER D WITH STROKE / LATIN SMALL LETTER D WITH STROKE
        {U'Ē', U'ē'}, // LATIN CAPITAL LETTER E WITH MACRON / LATIN SMALL LETTER E WITH MACRON
        {U'Ĕ', U'ĕ'}, // LATIN CAPITAL LETTER E WITH BREVE / LATIN SMALL LETTER E WITH BREVE
        {U'Ė', U'ė'}, // LATIN CAPITAL LETTER E WITH DOT ABOVE / LATIN SMALL LETTER E WITH DOT ABOVE
        {U'Ę', U'ę'}, // LATIN CAPITAL LETTER E WITH OGONEK / LATIN SMALL LETTER E WITH OGONEK
        {U'Ě', U'ě'}, // LATIN CAPITAL LETTER E WITH CARON / LATIN SMALL LETTER E WITH CARON
        {U'Ĝ', U'ĝ'}, // LATIN CAPITAL LETTER G WITH CIRCUMFLEX / LATIN SMALL LETTER G WITH CIRCUMFLEX
        {U'Ğ', U'ğ'}, // LATIN CAPITAL LETTER G WITH BREVE / LATIN SMALL LETTER G WITH BREVE
        {U'Ġ', U'ġ'}, // LATIN CAPITAL LETTER G WITH DOT ABOVE / LATIN SMALL LETTER G WITH DOT ABOVE
        {U'Ģ', U'ģ'}, // LATIN CAPITAL LETTER G WITH CEDILLA / LATIN SMALL LETTER G WITH CEDILLA
        {U'Ĥ', U'ĥ'}, // LATIN CAPITAL LETTER H WITH CIRCUMFLEX / LATIN SMALL LETTER H WITH CIRCUMFLEX
        {U'Ħ', U'ħ'}, // LATIN CAPITAL LETTER H WITH STROKE / LATIN SMALL LETTER H WITH STROKE
        {U'Ĩ', U'ĩ'}, // LATIN CAPITAL LETTER I WITH TILDE / LATIN SMALL LETTER I WITH TILDE
        {U'Ī', U'ī'}, // LATIN CAPITAL LETTER I WITH MACRON / LATIN SMALL LETTER I WITH MACRON
        {U'Ĭ', U'ĭ'}, // LATIN CAPITAL LETTER I WITH BREVE / LATIN SMALL LETTER I WITH BREVE
        {U'Į', U'į'}, // LATIN CAPITAL LETTER I WITH OGONEK / LATIN SMALL LETTER I WITH OGONEK
        {U'İ', U'i'}, // LATIN CAPITAL LETTER I WITH DOT ABOVE / LATIN SMALL LETTER I
        {U'Ĳ', U'ĳ'}, // LATIN CAPITAL LIGATURE IJ / LATIN SMALL LIGATURE IJ
        {U'Ĵ', U'ĵ'}, // LATIN CAPITAL LETTER J WITH CIRCUMFLEX / LATIN SMALL LETTER J WITH CIRCUMFLEX
        {U'Ķ', U'ķ'}, // LATIN CAPITAL LETTER K WITH CEDILLA / LATIN SMALL LETTER K WITH CEDILLA
        {U'Ĺ', U'ĺ'}, // LATIN CAPITAL LETTER L WITH ACUTE / LATIN SMALL LETTER L WITH ACUTE
        {U'Ļ', U'ļ'}, // LATIN CAPITAL LETTER L WITH CEDILLA / LATIN SMALL LETTER L WITH CEDILLA
        {U'Ľ', U'ľ'}, // LATIN CAPITAL LETTER L WITH CARON / LATIN SMALL LETTER L WITH CARON
        {U'Ŀ', U'ŀ'}, // LATIN CAPITAL LETTER L WITH MIDDLE DOT / LATIN SMALL LETTER L WITH MIDDLE DOT
        {U'Ł', U'ł'}, // LATIN CAPITAL LETTER L WITH STROKE / LATIN SMALL LETTER L WITH STROKE
        {U'Ń', U'ń'}, // LATIN CAPITAL LETTER N WITH ACUTE / LATIN SMALL LETTER N WITH ACUTE
        {U'Ņ', U'ņ'}, // LATIN CAPITAL LETTER N WITH CEDILLA / LATIN SMALL LETTER N WITH CEDILLA
        {U'Ň', U'ň'}, // LATIN CAPITAL LETTER N WITH CARON / LATIN SMALL LETTER N WITH CARON
        {U'Ŋ', U'ŋ'}, // LATIN CAPITAL LETTER ENG / LATIN SMALL LETTER ENG
        {U'Ō', U'ō'}, // LATIN CAPITAL LETTER O WITH MACRON / LATIN SMALL LETTER O WITH MACRON
        {U'Ŏ', U'ŏ'}, // LATIN CAPITAL LETTER O WITH BREVE / LATIN SMALL LETTER O WITH BREVE
        {U'Ő', U'ő'}, // LATIN CAPITAL LETTER O WITH DOUBLE ACUTE / LATIN SMALL LETTER O WITH DOUBLE ACUTE
        {U'Œ', U'œ'}, // LATIN CAPITAL LIGATURE OE / LATIN SMALL LIGATURE OE
        {U'Ŕ', U'ŕ'}, // LATIN CAPITAL LETTER R WITH ACUTE / LATIN SMALL LETTER R WITH ACUTE
        {U'Ŗ', U'ŗ'}, // LATIN CAPITAL LETTER R WITH CEDILLA / LATIN SMALL LETTER R WITH CEDILLA
        {U'Ř', U'ř'}, // LATIN CAPITAL LETTER R WITH CARON / LATIN SMALL LETTER R WITH CARON
        {U'Ś', U'ś'}, // LATIN CAPITAL LETTER S WITH ACUTE / LATIN SMALL LETTER S WITH ACUTE
        {U'Ŝ', U'ŝ'}, // LATIN CAPITAL LETTER S WITH CIRCUMFLEX / LATIN SMALL LETTER S WITH CIRCUMFLEX
        {U'Ş', U'ş'}, // LATIN CAPITAL LETTER S WITH CEDILLA / LATIN SMALL LETTER S WITH CEDILLA
        {U'Š', U'š'}, // LATIN CAPITAL LETTER S WITH CARON / LATIN SMALL LETTER S WITH CARON
        {U'Ţ', U'ţ'}, // LATIN CAPITAL LETTER T WITH CEDILLA / LATIN SMALL LETTER T WITH CEDILLA
        {U'Ť', U'ť'}, // LATIN CAPITAL LETTER T WITH CARON / LATIN SMALL LETTER T WITH CARON
        {U'Ŧ', U'ŧ'}, // LATIN CAPITAL LETTER T WITH STROKE / LATIN SMALL LETTER T WITH STROKE
        {U'Ũ', U'ũ'}, // LATIN CAPITAL LETTER U WITH TILDE / LATIN SMALL LETTER U WITH TILDE
        {U'Ū', U'ū'}, // LATIN CAPITAL LETTER U WITH MACRON / LATIN SMALL LETTER U WITH MACRON
        {U'Ŭ', U'ŭ'}, // LATIN CAPITAL LETTER U WITH BREVE / LATIN SMALL LETTER U WITH BREVE
        {U'Ů', U'ů'}, // LATIN CAPITAL LETTER U WITH RING ABOVE / LATIN SMALL LETTER U WITH RING ABOVE
        {U'Ű', U'ű'}, // LATIN CAPITAL LETTER U WITH DOUBLE ACUTE / LATIN SMALL LETTER U WITH DOUBLE ACUTE
        {U'Ų', U'ų'}, // LATIN CAPITAL LETTER U WITH OGONEK / LATIN SMALL LETTER U WITH OGONEK
        {U'Ŵ', U'ŵ'}, // LATIN CAPITAL LETTER W WITH CIRCUMFLEX / LATIN SMALL LETTER W WITH CIRCUMFLEX
        {U'Ŷ', U'ŷ'}, // LATIN CAPITAL LETTER Y WITH CIRCUMFLEX / LATIN SMALL LETTER Y WITH CIRCUMFLEX
        {U'Ÿ', U'ÿ'}, // LATIN CAPITAL LETTER Y WITH DIAERESIS / LATIN SMALL LETTER Y WITH DIAERESIS
        {U'Ź', U'ź'}, // LATIN CAPITAL LETTER Z WITH ACUTE / LATIN SMALL LETTER Z WITH ACUTE
        {U'Ż', U'ż'}, // LATIN CAPITAL LETTER Z WITH DOT ABOVE / LATIN SMALL LETTER Z WITH DOT ABOVE
        {U'Ž', U'ž'}, // LATIN CAPITAL LETTER Z WITH CARON / LATIN SMALL LETTER Z WITH CARON
        {U'Ɓ', U'ɓ'}, // LATIN CAPITAL LETTER B WITH HOOK / LATIN SMALL LETTER B WITH HOOK
        {U'Ƃ', U'ƃ'}, // LATIN CAPITAL LETTER B WITH TOPBAR / LATIN SMALL LETTER B WITH TOPBAR
        {U'Ƅ', U'ƅ'}, // LATIN CAPITAL LETTER TONE SIX / LATIN SMALL LETTER TONE SIX
        {U'Ɔ', U'ɔ'}, // LATIN CAPITAL LETTER OPEN O / LATIN SMALL LETTER OPEN O
        {U'Ƈ', U'ƈ'}, // LATIN CAPITAL LETTER C WITH HOOK / LATIN SMALL LETTER C WITH HOOK
        {U'Ɖ', U'ɖ'}, // LATIN CAPITAL LETTER AFRICAN D / LATIN SMALL LETTER D WITH TAIL
        {U'Ɗ', U'ɗ'}, // LATIN CAPITAL LETTER D WITH HOOK / LATIN SMALL LETTER D WITH HOOK
        {U'Ƌ', U'ƌ'}, // LATIN CAPITAL LETTER D WITH TOPBAR / LATIN SMALL LETTER D WITH TOPBAR
        {U'Ǝ', U'ǝ'}, // LATIN CAPITAL LETTER REVERSED E / LATIN SMALL LETTER TURNED E
        {U'Ə', U'ə'}, // LATIN CAPITAL LETTER SCHWA / LATIN SMALL LETTER SCHWA
        {U'Ɛ', U'ɛ'}, // LATIN CAPITAL LETTER OPEN E / LATIN SMALL LETTER OPEN E
        {U'Ƒ', U'ƒ'}, // LATIN CAPITAL LETTER F WITH HOOK / LATIN SMALL LETTER F WITH HOOK
        {U'Ɠ', U'ɠ'}, // LATIN CAPITAL LETTER G WITH HOOK / LATIN SMALL LETTER G WITH HOOK
        {U'Ɣ', U'ɣ'}, // LATIN CAPITAL LETTER GAMMA / LATIN SMALL LETTER GAMMA
        {U'Ɩ', U'ɩ'}, // LATIN CAPITAL LETTER IOTA / LATIN SMALL LETTER IOTA
        {U'Ɨ', U'ɨ'}, // LATIN CAPITAL LETTER I WITH STROKE / LATIN SMALL LETTER I WITH STROKE
        {U'Ƙ', U'ƙ'}, // LATIN CAPITAL LETTER K WITH HOOK / LATIN SMALL LETTER K WITH HOOK
        {U'Ɯ', U'ɯ'}, // LATIN CAPITAL LETTER TURNED M / LATIN SMALL LETTER TURNED M
        {U'Ɲ', U'ɲ'}, // LATIN CAPITAL LETTER N WITH LEFT HOOK / LATIN SMALL LETTER N WITH LEFT HOOK
        {U'Ɵ', U'ɵ'}, // LATIN CAPITAL LETTER O WITH MIDDLE TILDE / LATIN SMALL LETTER BARRED O
        {U'Ơ', U'ơ'}, // LATIN CAPITAL LETTER O WITH HORN / LATIN SMALL LETTER O WITH HORN
        {U'Ƣ', U'ƣ'}, // LATIN CAPITAL LETTER OI / LATIN SMALL LETTER OI
        {U'Ƥ', U'ƥ'}, // LATIN CAPITAL LETTER P WITH HOOK / LATIN SMALL LETTER P WITH HOOK
        {U'Ʀ', U'ʀ'}, // LATIN LETTER YR / LATIN LETTER SMALL CAPITAL R
        {U'Ƨ', U'ƨ'}, // LATIN CAPITAL LETTER TONE TWO / LATIN SMALL LETTER TONE TWO
        {U'Ʃ', U'ʃ'}, // LATIN CAPITAL LETTER ESH / LATIN SMALL LETTER ESH
        {U'Ƭ', U'ƭ'}, // LATIN CAPITAL LETTER T WITH HOOK / LATIN SMALL LETTER T WITH HOOK
        {U'Ʈ', U'ʈ'}, // LATIN CAPITAL LETTER T WITH RETROFLEX HOOK / LATIN SMALL LETTER T WITH RETROFLEX HOOK
        {U'Ư', U'ư'}, // LATIN CAPITAL LETTER U WITH HORN / LATIN SMALL LETTER U WITH HORN
        {U'Ʊ', U'ʊ'}, // LATIN CAPITAL LETTER UPSILON / LATIN SMALL LETTER UPSILON
        {U'Ʋ', U'ʋ'}, // LATIN CAPITAL LETTER V WITH HOOK / LATIN SMALL LETTER V WITH HOOK
        {U'Ƴ', U'ƴ'}, // LATIN CAPITAL LETTER Y WITH HOOK / LATIN SMALL LETTER Y WITH HOOK
        {U'Ƶ', U'ƶ'}, // LATIN CAPITAL LETTER Z WITH STROKE / LATIN SMALL LETTER Z WITH STROKE
        {U'Ʒ', U'ʒ'}, // LATIN CAPITAL LETTER EZH / LATIN SMALL LETTER EZH
        {U'Ƹ', U'ƹ'}, // LATIN CAPITAL LETTER EZH REVERSED / LATIN SMALL LETTER EZH REVERSED
        {U'Ƽ', U'ƽ'}, // LATIN CAPITAL LETTER TONE FIVE / LATIN SMALL LETTER TONE FIVE
        {U'Ǆ', U'ǆ'}, // LATIN CAPITAL LETTER DZ WITH CARON / LATIN SMALL LETTER DZ WITH CARON
        {U'ǅ', U'ǆ'}, // LATIN CAPITAL LETTER D WITH SMALL LETTER Z WITH CARON / LATIN SMALL LETTER DZ WITH CARON
        {U'Ǉ', U'ǉ'}, // LATIN CAPITAL LETTER LJ / LATIN SMALL LETTER LJ
        {U'ǈ', U'ǉ'}, // LATIN CAPITAL LETTER L WITH SMALL LETTER J / LATIN SMALL LETTER LJ
        {U'Ǌ', U'ǌ'}, // LATIN CAPITAL LETTER NJ / LATIN SMALL LETTER NJ
        {U'ǋ', U'ǌ'}, // LATIN CAPITAL LETTER N WITH SMALL LETTER J / LATIN SMALL LETTER NJ
        {U'Ǎ', U'ǎ'}, // LATIN CAPITAL LETTER A WITH CARON / LATIN SMALL LETTER A WITH CARON
        {U'Ǐ', U'ǐ'}, // LATIN CAPITAL LETTER I WITH CARON / LATIN SMALL LETTER I WITH CARON
        {U'Ǒ', U'ǒ'}, // LATIN CAPITAL LETTER O WITH CARON / LATIN SMALL LETTER O WITH CARON
        {U'Ǔ', U'ǔ'}, // LATIN CAPITAL LETTER U WITH CARON / LATIN SMALL LETTER U WITH CARON
        {U'Ǖ', U'ǖ'}, // LATIN CAPITAL LETTER U WITH DIAERESIS AND MACRON / LATIN SMALL LETTER U WITH DIAERESIS AND MACRON
        {U'Ǘ', U'ǘ'}, // LATIN CAPITAL LETTER U WITH DIAERESIS AND ACUTE / LATIN SMALL LETTER U WITH DIAERESIS AND ACUTE
        {U'Ǚ', U'ǚ'}, // LATIN CAPITAL LETTER U WITH DIAERESIS AND CARON / LATIN SMALL LETTER U WITH DIAERESIS AND CARON
        {U'Ǜ', U'ǜ'}, // LATIN CAPITAL LETTER U WITH DIAERESIS AND GRAVE / LATIN SMALL LETTER U WITH DIAERESIS AND GRAVE
        {U'Ǟ', U'ǟ'}, // LATIN CAPITAL LETTER A WITH DIAERESIS AND MACRON / LATIN SMALL LETTER A WITH DIAERESIS AND MACRON
        {U'Ǡ', U'ǡ'}, // LATIN CAPITAL LETTER A WITH DOT ABOVE AND MACRON / LATIN SMALL LETTER A WITH DOT ABOVE AND MACRON
        {U'Ǣ', U'ǣ'}, // LATIN CAPITAL LETTER AE WITH MACRON / LATIN SMALL LETTER AE WITH MACRON
        {U'Ǥ', U'ǥ'}, // LATIN CAPITAL LETTER G WITH STROKE / LATIN SMALL LETTER G WITH STROKE
        {U'Ǧ', U'ǧ'}, // LATIN CAPITAL LETTER G WITH CARON / LATIN SMALL LETTER G WITH CARON
        {U'Ǩ', U'ǩ'}, // LATIN CAPITAL LETTER K WITH CARON / LATIN SMALL LETTER K WITH CARON
        {U'Ǫ', U'ǫ'}, // LATIN CAPITAL LETTER O WITH OGONEK / LATIN SMALL LETTER O WITH OGONEK
        {U'Ǭ', U'ǭ'}, // LATIN CAPITAL LETTER O WITH OGONEK AND MACRON / LATIN SMALL LETTER O WITH OGONEK AND MACRON
        {U'Ǯ', U'ǯ'}, // LATIN CAPITAL LETTER EZH WITH CARON / LATIN SMALL LETTER EZH WITH CARON
        {U'Ǳ', U'ǳ'}, // LATIN CAPITAL LETTER DZ / LATIN SMALL LETTER DZ
        {U'ǲ', U'ǳ'}, // LATIN CAPITAL LETTER D WITH SMALL LETTER Z / LATIN SMALL LETTER DZ
        {U'Ǵ', U'ǵ'}, // LATIN CAPITAL LETTER G WITH ACUTE / LATIN SMALL LETTER G WITH ACUTE
        {U'Ƕ', U'ƕ'}, // LATIN CAPITAL LETTER HWAIR / LATIN SMALL LETTER HV
        {U'Ƿ', U'ƿ'}, // LATIN CAPITAL LETTER WYNN / LATIN LETTER WYNN
        {U'Ǹ', U'ǹ'}, // LATIN CAPITAL LETTER N WITH GRAVE / LATIN SMALL LETTER N WITH GRAVE
        {U'Ǻ', U'ǻ'}, // LATIN CAPITAL LETTER A WITH RING ABOVE AND ACUTE / LATIN SMALL LETTER A WITH RING ABOVE AND ACUTE
        {U'Ǽ', U'ǽ'}, // LATIN CAPITAL LETTER AE WITH ACUTE / LATIN SMALL LETTER AE WITH ACUTE
        {U'Ǿ', U'ǿ'}, // LATIN CAPITAL LETTER O WITH STROKE AND ACUTE / LATIN SMALL LETTER O WITH STROKE AND ACUTE
        {U'Ȁ', U'ȁ'}, // LATIN CAPITAL LETTER A WITH DOUBLE GRAVE / LATIN SMALL LETTER A WITH DOUBLE GRAVE
        {U'Ȃ', U'ȃ'}, // LATIN CAPITAL LETTER A WITH INVERTED BREVE / LATIN SMALL LETTER A WITH INVERTED BREVE
        {U'Ȅ', U'ȅ'}, // LATIN CAPITAL LETTER E WITH DOUBLE GRAVE / LATIN SMALL LETTER E WITH DOUBLE GRAVE
        {U'Ȇ', U'ȇ'}, // LATIN CAPITAL LETTER E WITH INVERTED BREVE / LATIN SMALL LETTER E WITH INVERTED BREVE
        {U'Ȉ', U'ȉ'}, // LATIN CAPITAL LETTER I WITH DOUBLE GRAVE / LATIN SMALL LETTER I WITH DOUBLE GRAVE
        {U'Ȋ', U'ȋ'}, // LATIN CAPITAL LETTER I WITH INVERTED BREVE / LATIN SMALL LETTER I WITH INVERTED BREVE
        {U'Ȍ', U'ȍ'}, // LATIN CAPITAL LETTER O WITH DOUBLE GRAVE / LATIN SMALL LETTER O WITH DOUBLE GRAVE
        {U'Ȏ', U'ȏ'}, // LATIN CAPITAL LETTER O WITH INVERTED BREVE / LATIN SMALL LETTER O WITH INVERTED BREVE
        {U'Ȑ', U'ȑ'}, // LATIN CAPITAL LETTER R WITH DOUBLE GRAVE / LATIN SMALL LETTER R WITH DOUBLE GRAVE
        {U'Ȓ', U'ȓ'}, // LATIN CAPITAL LETTER R WITH INVERTED BREVE / LATIN SMALL LETTER R WITH INVERTED BREVE
        {U'Ȕ', U'ȕ'}, // LATIN CAPITAL LETTER U WITH DOUBLE GRAVE / LATIN SMALL LETTER U WITH DOUBLE GRAVE
        {U'Ȗ', U'ȗ'}, // LATIN CAPITAL LETTER U WITH INVERTED BREVE / LATIN SMALL LETTER U WITH INVERTED BREVE
        {U'Ș', U'ș'}, // LATIN CAPITAL LETTER S WITH COMMA BELOW / LATIN SMALL LETTER S WITH COMMA BELOW
        {U'Ț', U'ț'}, // LATIN CAPITAL LETTER T WITH COMMA BELOW / LATIN SMALL LETTER T WITH COMMA BELOW
        {U'Ȝ', U'ȝ'}, // LATIN CAPITAL LETTER YOGH / LATIN SMALL LETTER YOGH
        {U'Ȟ', U'ȟ'}, // LATIN CAPITAL LETTER H WITH CARON / LATIN SMALL LETTER H WITH CARON
        {U'Ƞ', U'ƞ'}, // LATIN CAPITAL LETTER N WITH LONG RIGHT LEG / LATIN SMALL LETTER N WITH LONG RIGHT LEG
        {U'Ȣ', U'ȣ'}, // LATIN CAPITAL LETTER OU / LATIN SMALL LETTER OU
        {U'Ȥ', U'ȥ'}, // LATIN CAPITAL LETTER Z WITH HOOK / LATIN SMALL LETTER Z WITH HOOK
        {U'Ȧ', U'ȧ'}, // LATIN CAPITAL LETTER A WITH DOT ABOVE / LATIN SMALL LETTER A WITH DOT ABOVE
        {U'Ȩ', U'ȩ'}, // LATIN CAPITAL LETTER E WITH CEDILLA / LATIN SMALL LETTER E WITH CEDILLA
        {U'Ȫ', U'ȫ'}, // LATIN CAPITAL LETTER O WITH DIAERESIS AND MACRON / LATIN SMALL LETTER O WITH DIAERESIS AND MACRON
        {U'Ȭ', U'ȭ'}, // LATIN CAPITAL LETTER O WITH TILDE AND MACRON / LATIN SMALL LETTER O WITH TILDE AND MACRON
        {U'Ȯ', U'ȯ'}, // LATIN CAPITAL LETTER O WITH DOT ABOVE / LATIN SMALL LETTER O WITH DOT ABOVE
        {U'Ȱ', U'ȱ'}, // LATIN CAPITAL LETTER O WITH DOT ABOVE AND MACRON / LATIN SMALL LETTER O WITH DOT ABOVE AND MACRON
        {U'Ȳ', U'ȳ'}, // LATIN CAPITAL LETTER Y WITH MACRON / LATIN SMALL LETTER Y WITH MACRON
        {U'Ⱥ', U'ⱥ'}, // LATIN CAPITAL LETTER A WITH STROKE / LATIN SMALL LETTER A WITH STROKE
        {U'Ȼ', U'ȼ'}, // LATIN CAPITAL LETTER C WITH STROKE / LATIN SMALL LETTER C WITH STROKE
        {U'Ƚ', U'ƚ'}, // LATIN CAPITAL LETTER L WITH BAR / LATIN SMALL LETTER L WITH BAR
        {U'Ⱦ', U'ⱦ'}, // LATIN CAPITAL LETTER T WITH DIAGONAL STROKE / LATIN SMALL LETTER T WITH DIAGONAL STROKE
        {U'Ɂ', U'ɂ'}, // LATIN CAPITAL LETTER GLOTTAL STOP / LATIN SMALL LETTER GLOTTAL STOP
        {U'Ƀ', U'ƀ'}, // LATIN CAPITAL LETTER B WITH STROKE / LATIN SMALL LETTER B WITH STROKE
        {U'Ʉ', U'ʉ'}, // LATIN CAPITAL LETTER U BAR / LATIN SMALL LETTER U BAR
        {U'Ʌ', U'ʌ'}, // LATIN CAPITAL LETTER TURNED V / LATIN SMALL LETTER TURNED V
        {U'Ɇ', U'ɇ'}, // LATIN CAPITAL LETTER E WITH STROKE / LATIN SMALL LETTER E WITH STROKE
        {U'Ɉ', U'ɉ'}, // LATIN CAPITAL LETTER J WITH STROKE / LATIN SMALL LETTER J WITH STROKE
        {U'Ɋ', U'ɋ'}, // LATIN CAPITAL LETTER SMALL Q WITH HOOK TAIL / LATIN SMALL LETTER Q WITH HOOK TAIL
        {U'Ɍ', U'ɍ'}, // LATIN CAPITAL LETTER R WITH STROKE / LATIN SMALL LETTER R WITH STROKE
        {U'Ɏ', U'ɏ'}, // LATIN CAPITAL LETTER Y WITH STROKE / LATIN SMALL LETTER Y WITH STROKE
        {U'Ͱ', U'ͱ'}, // GREEK CAPITAL LETTER HETA / GREEK SMALL LETTER HETA
        {U'Ͳ', U'ͳ'}, // GREEK CAPITAL LETTER ARCHAIC SAMPI / GREEK SMALL LETTER ARCHAIC SAMPI
        {U'Ͷ', U'ͷ'}, // GREEK CAPITAL LETTER PAMPHYLIAN DIGAMMA / GREEK SMALL LETTER PAMPHYLIAN DIGAMMA
        {U'Ϳ', U'ϳ'}, // GREEK CAPITAL LETTER YOT / GREEK LETTER YOT
        {U'Ά', U'ά'}, // GREEK CAPITAL LETTER ALPHA WITH TONOS / GREEK SMALL LETTER ALPHA WITH TONOS
        {U'Έ', U'έ'}, // GREEK CAPITAL LETTER EPSILON WITH TONOS / GREEK SMALL LETTER EPSILON WITH TONOS
        {U'Ή', U'ή'}, // GREEK CAPITAL LETTER ETA WITH TONOS / GREEK SMALL LETTER ETA WITH TONOS
        {U'Ί', U'ί'}, // GREEK CAPITAL LETTER IOTA WITH TONOS / GREEK SMALL LETTER IOTA WITH TONOS
        {U'Ό', U'ό'}, // GREEK CAPITAL LETTER OMICRON WITH TONOS / GREEK SMALL LETTER OMICRON WITH TONOS
        {U'Ύ', U'ύ'}, // GREEK CAPITAL LETTER UPSILON WITH TONOS / GREEK SMALL LETTER UPSILON WITH TONOS
        {U'Ώ', U'ώ'}, // GREEK CAPITAL LETTER OMEGA WITH TONOS / GREEK SMALL LETTER OMEGA WITH TONOS
        {U'Α', U'α'}, // GREEK CAPITAL LETTER ALPHA / GREEK SMALL LETTER ALPHA
        {U'Β', U'β'}, // GREEK CAPITAL LETTER BETA / GREEK SMALL LETTER BETA
        {U'Γ', U'γ'}, // GREEK CAPITAL LETTER GAMMA / GREEK SMALL LETTER GAMMA
        {U'Δ', U'δ'}, // GREEK CAPITAL LETTER DELTA / GREEK SMALL LETTER DELTA
        {U'Ε', U'ε'}, // GREEK CAPITAL LETTER EPSILON / GREEK SMALL LETTER EPSILON
        {U'Ζ', U'ζ'}, // GREEK CAPITAL LETTER ZETA / GREEK SMALL LETTER ZETA
        {U'Η', U'η'}, // GREEK CAPITAL LETTER ETA / GREEK SMALL LETTER ETA
        {U'Θ', U'θ'}, // GREEK CAPITAL LETTER THETA / GREEK SMALL LETTER THETA
        {U'Ι', U'ι'}, // GREEK CAPITAL LETTER IOTA / GREEK SMALL LETTER IOTA
        {U'Κ', U'κ'}, // GREEK CAPITAL LETTER KAPPA / GREEK SMALL LETTER KAPPA
        {U'Λ', U'λ'}, // GREEK CAPITAL LETTER LAMDA / GREEK SMALL LETTER LAMDA
        {U'Μ', U'μ'}, // GREEK CAPITAL LETTER MU / GREEK SMALL LETTER MU
        {U'Ν', U'ν'}, // GREEK CAPITAL LETTER NU / GREEK SMALL LETTER NU
        {U'Ξ', U'ξ'}, // GREEK CAPITAL LETTER XI / GREEK SMALL LETTER XI
        {U'Ο', U'ο'}, // GREEK CAPITAL LETTER OMICRON / GREEK SMALL LETTER OMICRON
        {U'Π', U'π'}, // GREEK CAPITAL LETTER PI / GREEK SMALL LETTER PI
        {U'Ρ', U'ρ'}, // GREEK CAPITAL LETTER RHO / GREEK SMALL LETTER RHO
        {U'Σ', U'σ'}, // GREEK CAPITAL LETTER SIGMA / GREEK SMALL LETTER SIGMA
        {U'Τ', U'τ'}, // GREEK CAPITAL LETTER TAU / GREEK SMALL LETTER TAU
        {U'Υ', U'υ'}, // GREEK CAPITAL LETTER UPSILON / GREEK SMALL LETTER UPSILON
        {U'Φ', U'φ'}, // GREEK CAPITAL LETTER PHI / GREEK SMALL LETTER PHI
        {U'Χ', U'χ'}, // GREEK CAPITAL LETTER CHI / GREEK SMALL LETTER CHI
        {U'Ψ', U'ψ'}, // GREEK CAPITAL LETTER PSI / GREEK SMALL LETTER PSI
        {U'Ω', U'ω'}, // GREEK CAPITAL LETTER OMEGA / GREEK SMALL LETTER OMEGA
        {U'Ϊ', U'ϊ'}, // GREEK CAPITAL LETTER IOTA WITH DIALYTIKA / GREEK SMALL LETTER IOTA WITH DIALYTIKA
        {U'Ϋ', U'ϋ'}, // GREEK CAPITAL LETTER UPSILON WITH DIALYTIKA / GREEK SMALL LETTER UPSILON WITH DIALYTIKA
        {U'Ϗ', U'ϗ'}, // GREEK CAPITAL KAI SYMBOL / GREEK KAI SYMBOL
        {U'Ϙ', U'ϙ'}, // GREEK LETTER ARCHAIC KOPPA / GREEK SMALL LETTER ARCHAIC KOPPA
        {U'Ϛ', U'ϛ'}, // GREEK LETTER STIGMA / GREEK SMALL LETTER STIGMA
        {U'Ϝ', U'ϝ'}, // GREEK LETTER DIGAMMA / GREEK SMALL LETTER DIGAMMA
        {U'Ϟ', U'ϟ'}, // GREEK LETTER KOPPA / GREEK SMALL LETTER KOPPA
        {U'Ϡ', U'ϡ'}, // GREEK LETTER SAMPI / GREEK SMALL LETTER SAMPI
        {U'Ϣ', U'ϣ'}, // COPTIC CAPITAL LETTER SHEI / COPTIC SMALL LETTER SHEI
        {U'Ϥ', U'ϥ'}, // COPTIC CAPITAL LETTER FEI / COPTIC SMALL LETTER FEI
        {U'Ϧ', U'ϧ'}, // COPTIC CAPITAL LETTER KHEI / COPTIC SMALL LETTER KHEI
        {U'Ϩ', U'ϩ'}, // COPTIC CAPITAL LETTER HORI / COPTIC SMALL LETTER HORI
        {U'Ϫ', U'ϫ'}, // COPTIC CAPITAL LETTER GANGIA / COPTIC SMALL LETTER GANGIA
        {U'Ϭ', U'ϭ'}, // COPTIC CAPITAL LETTER SHIMA / COPTIC SMALL LETTER SHIMA
        {U'Ϯ', U'ϯ'}, // COPTIC CAPITAL LETTER DEI / COPTIC SMALL LETTER DEI
        {U'ϴ', U'θ'}, // GREEK CAPITAL THETA SYMBOL / GREEK SMALL LETTER THETA
        {U'Ϸ', U'ϸ'}, // GREEK CAPITAL LETTER SHO / GREEK SMALL LETTER SHO
        {U'Ϲ', U'ϲ'}, // GREEK CAPITAL LUNATE SIGMA SYMBOL / GREEK LUNATE SIGMA SYMBOL
        {U'Ϻ', U'ϻ'}, // GREEK CAPITAL LETTER SAN / GREEK SMALL LETTER SAN
        {U'Ͻ', U'ͻ'}, // GREEK CAPITAL REVERSED LUNATE SIGMA SYMBOL / GREEK SMALL REVERSED LUNATE SIGMA SYMBOL
        {U'Ͼ', U'ͼ'}, // GREEK CAPITAL DOTTED LUNATE SIGMA SYMBOL / GREEK SMALL DOTTED LUNATE SIGMA SYMBOL
        {U'Ͽ', U'ͽ'},
        // GREEK CAPITAL REVERSED DOTTED LUNATE SIGMA SYMBOL / GREEK SMALL REVERSED DOTTED LUNATE SIGMA SYMBOL
        {U'Ѐ', U'ѐ'}, // CYRILLIC CAPITAL LETTER IE WITH GRAVE / CYRILLIC SMALL LETTER IE WITH GRAVE
        {U'Ё', U'ё'}, // CYRILLIC CAPITAL LETTER IO / CYRILLIC SMALL LETTER IO
        {U'Ђ', U'ђ'}, // CYRILLIC CAPITAL LETTER DJE / CYRILLIC SMALL LETTER DJE
        {U'Ѓ', U'ѓ'}, // CYRILLIC CAPITAL LETTER GJE / CYRILLIC SMALL LETTER GJE
        {U'Є', U'є'}, // CYRILLIC CAPITAL LETTER UKRAINIAN IE / CYRILLIC SMALL LETTER UKRAINIAN IE
        {U'Ѕ', U'ѕ'}, // CYRILLIC CAPITAL LETTER DZE / CYRILLIC SMALL LETTER DZE
        {U'І', U'і'},
        // CYRILLIC CAPITAL LETTER BYELORUSSIAN-UKRAINIAN I / CYRILLIC SMALL LETTER BYELORUSSIAN-UKRAINIAN I
        {U'Ї', U'ї'}, // CYRILLIC CAPITAL LETTER YI / CYRILLIC SMALL LETTER YI
        {U'Ј', U'ј'}, // CYRILLIC CAPITAL LETTER JE / CYRILLIC SMALL LETTER JE
        {U'Љ', U'љ'}, // CYRILLIC CAPITAL LETTER LJE / CYRILLIC SMALL LETTER LJE
        {U'Њ', U'њ'}, // CYRILLIC CAPITAL LETTER NJE / CYRILLIC SMALL LETTER NJE
        {U'Ћ', U'ћ'}, // CYRILLIC CAPITAL LETTER TSHE / CYRILLIC SMALL LETTER TSHE
        {U'Ќ', U'ќ'}, // CYRILLIC CAPITAL LETTER KJE / CYRILLIC SMALL LETTER KJE
        {U'Ѝ', U'ѝ'}, // CYRILLIC CAPITAL LETTER I WITH GRAVE / CYRILLIC SMALL LETTER I WITH GRAVE
        {U'Ў', U'ў'}, // CYRILLIC CAPITAL LETTER SHORT U / CYRILLIC SMALL LETTER SHORT U
        {U'Џ', U'џ'}, // CYRILLIC CAPITAL LETTER DZHE / CYRILLIC SMALL LETTER DZHE
        {U'А', U'а'}, // CYRILLIC CAPITAL LETTER A / CYRILLIC SMALL LETTER A
        {U'Б', U'б'}, // CYRILLIC CAPITAL LETTER BE / CYRILLIC SMALL LETTER BE
        {U'В', U'в'}, // CYRILLIC CAPITAL LETTER VE / CYRILLIC SMALL LETTER VE
        {U'Г', U'г'}, // CYRILLIC CAPITAL LETTER GHE / CYRILLIC SMALL LETTER GHE
        {U'Д', U'д'}, // CYRILLIC CAPITAL LETTER DE / CYRILLIC SMALL LETTER DE
        {U'Е', U'е'}, // CYRILLIC CAPITAL LETTER IE / CYRILLIC SMALL LETTER IE
        {U'Ж', U'ж'}, // CYRILLIC CAPITAL LETTER ZHE / CYRILLIC SMALL LETTER ZHE
        {U'З', U'з'}, // CYRILLIC CAPITAL LETTER ZE / CYRILLIC SMALL LETTER ZE
        {U'И', U'и'}, // CYRILLIC CAPITAL LETTER I / CYRILLIC SMALL LETTER I
        {U'Й', U'й'}, // CYRILLIC CAPITAL LETTER SHORT I / CYRILLIC SMALL LETTER SHORT I
        {U'К', U'к'}, // CYRILLIC CAPITAL LETTER KA / CYRILLIC SMALL LETTER KA
        {U'Л', U'л'}, // CYRILLIC CAPITAL LETTER EL / CYRILLIC SMALL LETTER EL
        {U'М', U'м'}, // CYRILLIC CAPITAL LETTER EM / CYRILLIC SMALL LETTER EM
        {U'Н', U'н'}, // CYRILLIC CAPITAL LETTER EN / CYRILLIC SMALL LETTER EN
        {U'О', U'о'}, // CYRILLIC CAPITAL LETTER O / CYRILLIC SMALL LETTER O
        {U'П', U'п'}, // CYRILLIC CAPITAL LETTER PE / CYRILLIC SMALL LETTER PE
        {U'Р', U'р'}, // CYRILLIC CAPITAL LETTER ER / CYRILLIC SMALL LETTER ER
        {U'С', U'с'}, // CYRILLIC CAPITAL LETTER ES / CYRILLIC SMALL LETTER ES
        {U'Т', U'т'}, // CYRILLIC CAPITAL LETTER TE / CYRILLIC SMALL LETTER TE
        {U'У', U'у'}, // CYRILLIC CAPITAL LETTER U / CYRILLIC SMALL LETTER U
        {U'Ф', U'ф'}, // CYRILLIC CAPITAL LETTER EF / CYRILLIC SMALL LETTER EF
        {U'Х', U'х'}, // CYRILLIC CAPITAL LETTER HA / CYRILLIC SMALL LETTER HA
        {U'Ц', U'ц'}, // CYRILLIC CAPITAL LETTER TSE / CYRILLIC SMALL LETTER TSE
        {U'Ч', U'ч'}, // CYRILLIC CAPITAL LETTER CHE / CYRILLIC SMALL LETTER CHE
        {U'Ш', U'ш'}, // CYRILLIC CAPITAL LETTER SHA / CYRILLIC SMALL LETTER SHA
        {U'Щ', U'щ'}, // CYRILLIC CAPITAL LETTER SHCHA / CYRILLIC SMALL LETTER SHCHA
        {U'Ъ', U'ъ'}, // CYRILLIC CAPITAL LETTER HARD SIGN / CYRILLIC SMALL LETTER HARD SIGN
        {U'Ы', U'ы'}, // CYRILLIC CAPITAL LETTER YERU / CYRILLIC SMALL LETTER YERU
        {U'Ь', U'ь'}, // CYRILLIC CAPITAL LETTER SOFT SIGN / CYRILLIC SMALL LETTER SOFT SIGN
        {U'Э', U'э'}, // CYRILLIC CAPITAL LETTER E / CYRILLIC SMALL LETTER E
        {U'Ю', U'ю'}, // CYRILLIC CAPITAL LETTER YU / CYRILLIC SMALL LETTER YU
        {U'Я', U'я'}, // CYRILLIC CAPITAL LETTER YA / CYRILLIC SMALL LETTER YA
        {U'Ѡ', U'ѡ'}, // CYRILLIC CAPITAL LETTER OMEGA / CYRILLIC SMALL LETTER OMEGA
        {U'Ѣ', U'ѣ'}, // CYRILLIC CAPITAL LETTER YAT / CYRILLIC SMALL LETTER YAT
        {U'Ѥ', U'ѥ'}, // CYRILLIC CAPITAL LETTER IOTIFIED E / CYRILLIC SMALL LETTER IOTIFIED E
        {U'Ѧ', U'ѧ'}, // CYRILLIC CAPITAL LETTER LITTLE YUS / CYRILLIC SMALL LETTER LITTLE YUS
        {U'Ѩ', U'ѩ'}, // CYRILLIC CAPITAL LETTER IOTIFIED LITTLE YUS / CYRILLIC SMALL LETTER IOTIFIED LITTLE YUS
        {U'Ѫ', U'ѫ'}, // CYRILLIC CAPITAL LETTER BIG YUS / CYRILLIC SMALL LETTER BIG YUS
        {U'Ѭ', U'ѭ'}, // CYRILLIC CAPITAL LETTER IOTIFIED BIG YUS / CYRILLIC SMALL LETTER IOTIFIED BIG YUS
        {U'Ѯ', U'ѯ'}, // CYRILLIC CAPITAL LETTER KSI / CYRILLIC SMALL LETTER KSI
        {U'Ѱ', U'ѱ'}, // CYRILLIC CAPITAL LETTER PSI / CYRILLIC SMALL LETTER PSI
        {U'Ѳ', U'ѳ'}, // CYRILLIC CAPITAL LETTER FITA / CYRILLIC SMALL LETTER FITA
        {U'Ѵ', U'ѵ'}, // CYRILLIC CAPITAL LETTER IZHITSA / CYRILLIC SMALL LETTER IZHITSA
        {U'Ѷ', U'ѷ'}, // CYRILLIC CAPITAL LETTER IZHITSA WITH DOUBLE GRAVE ACCENT / CYRILLIC SMALL LETTER IZHITSA WITH DOUBLE GRAVE ACCENT
        {U'Ѹ', U'ѹ'}, // CYRILLIC CAPITAL LETTER UK / CYRILLIC SMALL LETTER UK
        {U'Ѻ', U'ѻ'}, // CYRILLIC CAPITAL LETTER ROUND OMEGA / CYRILLIC SMALL LETTER ROUND OMEGA
        {U'Ѽ', U'ѽ'}, // CYRILLIC CAPITAL LETTER OMEGA WITH TITLO / CYRILLIC SMALL LETTER OMEGA WITH TITLO
        {U'Ѿ', U'ѿ'}, // CYRILLIC CAPITAL LETTER OT / CYRILLIC SMALL LETTER OT
        {U'Ҁ', U'ҁ'}, // CYRILLIC CAPITAL LETTER KOPPA / CYRILLIC SMALL LETTER KOPPA
        {U'Ҋ', U'ҋ'}, // CYRILLIC CAPITAL LETTER SHORT I WITH TAIL / CYRILLIC SMALL LETTER SHORT I WITH TAIL
        {U'Ҍ', U'ҍ'}, // CYRILLIC CAPITAL LETTER SEMISOFT SIGN / CYRILLIC SMALL LETTER SEMISOFT SIGN
        {U'Ҏ', U'ҏ'}, // CYRILLIC CAPITAL LETTER ER WITH TICK / CYRILLIC SMALL LETTER ER WITH TICK
        {U'Ґ', U'ґ'}, // CYRILLIC CAPITAL LETTER GHE WITH UPTURN / CYRILLIC SMALL LETTER GHE WITH UPTURN
        {U'Ғ', U'ғ'}, // CYRILLIC CAPITAL LETTER GHE WITH STROKE / CYRILLIC SMALL LETTER GHE WITH STROKE
        {U'Ҕ', U'ҕ'}, // CYRILLIC CAPITAL LETTER GHE WITH MIDDLE HOOK / CYRILLIC SMALL LETTER GHE WITH MIDDLE HOOK
        {U'Җ', U'җ'}, // CYRILLIC CAPITAL LETTER ZHE WITH DESCENDER / CYRILLIC SMALL LETTER ZHE WITH DESCENDER
        {U'Ҙ', U'ҙ'}, // CYRILLIC CAPITAL LETTER ZE WITH DESCENDER / CYRILLIC SMALL LETTER ZE WITH DESCENDER
        {U'Қ', U'қ'}, // CYRILLIC CAPITAL LETTER KA WITH DESCENDER / CYRILLIC SMALL LETTER KA WITH DESCENDER
        {U'Ҝ', U'ҝ'}, // CYRILLIC CAPITAL LETTER KA WITH VERTICAL STROKE / CYRILLIC SMALL LETTER KA WITH VERTICAL STROKE
        {U'Ҟ', U'ҟ'}, // CYRILLIC CAPITAL LETTER KA WITH STROKE / CYRILLIC SMALL LETTER KA WITH STROKE
        {U'Ҡ', U'ҡ'}, // CYRILLIC CAPITAL LETTER BASHKIR KA / CYRILLIC SMALL LETTER BASHKIR KA
        {U'Ң', U'ң'}, // CYRILLIC CAPITAL LETTER EN WITH DESCENDER / CYRILLIC SMALL LETTER EN WITH DESCENDER
        {U'Ҥ', U'ҥ'}, // CYRILLIC CAPITAL LIGATURE EN GHE / CYRILLIC SMALL LIGATURE EN GHE
        {U'Ҧ', U'ҧ'}, // CYRILLIC CAPITAL LETTER PE WITH MIDDLE HOOK / CYRILLIC SMALL LETTER PE WITH MIDDLE HOOK
        {U'Ҩ', U'ҩ'}, // CYRILLIC CAPITAL LETTER ABKHASIAN HA / CYRILLIC SMALL LETTER ABKHASIAN HA
        {U'Ҫ', U'ҫ'}, // CYRILLIC CAPITAL LETTER ES WITH DESCENDER / CYRILLIC SMALL LETTER ES WITH DESCENDER
        {U'Ҭ', U'ҭ'}, // CYRILLIC CAPITAL LETTER TE WITH DESCENDER / CYRILLIC SMALL LETTER TE WITH DESCENDER
        {U'Ү', U'ү'}, // CYRILLIC CAPITAL LETTER STRAIGHT U / CYRILLIC SMALL LETTER STRAIGHT U
        {U'Ұ', U'ұ'}, // CYRILLIC CAPITAL LETTER STRAIGHT U WITH STROKE / CYRILLIC SMALL LETTER STRAIGHT U WITH STROKE
        {U'Ҳ', U'ҳ'}, // CYRILLIC CAPITAL LETTER HA WITH DESCENDER / CYRILLIC SMALL LETTER HA WITH DESCENDER
        {U'Ҵ', U'ҵ'}, // CYRILLIC CAPITAL LIGATURE TE TSE / CYRILLIC SMALL LIGATURE TE TSE
        {U'Ҷ', U'ҷ'}, // CYRILLIC CAPITAL LETTER CHE WITH DESCENDER / CYRILLIC SMALL LETTER CHE WITH DESCENDER
        {U'Ҹ', U'ҹ'}, // CYRILLIC CAPITAL LETTER CHE WITH VERTICAL STROKE / CYRILLIC SMALL LETTER CHE WITH VERTICAL STROKE
        {U'Һ', U'һ'}, // CYRILLIC CAPITAL LETTER SHHA / CYRILLIC SMALL LETTER SHHA
        {U'Ҽ', U'ҽ'}, // CYRILLIC CAPITAL LETTER ABKHASIAN CHE / CYRILLIC SMALL LETTER ABKHASIAN CHE
        {U'Ҿ', U'ҿ'}, // CYRILLIC CAPITAL LETTER ABKHASIAN CHE WITH DESCENDER / CYRILLIC SMALL LETTER ABKHASIAN CHE WITH DESCENDER
        {U'Ӏ', U'ӏ'}, // CYRILLIC LETTER PALOCHKA / CYRILLIC SMALL LETTER PALOCHKA
        {U'Ӂ', U'ӂ'}, // CYRILLIC CAPITAL LETTER ZHE WITH BREVE / CYRILLIC SMALL LETTER ZHE WITH BREVE
        {U'Ӄ', U'ӄ'}, // CYRILLIC CAPITAL LETTER KA WITH HOOK / CYRILLIC SMALL LETTER KA WITH HOOK
        {U'Ӆ', U'ӆ'}, // CYRILLIC CAPITAL LETTER EL WITH TAIL / CYRILLIC SMALL LETTER EL WITH TAIL
        {U'Ӈ', U'ӈ'}, // CYRILLIC CAPITAL LETTER EN WITH HOOK / CYRILLIC SMALL LETTER EN WITH HOOK
        {U'Ӊ', U'ӊ'}, // CYRILLIC CAPITAL LETTER EN WITH TAIL / CYRILLIC SMALL LETTER EN WITH TAIL
        {U'Ӌ', U'ӌ'}, // CYRILLIC CAPITAL LETTER KHAKASSIAN CHE / CYRILLIC SMALL LETTER KHAKASSIAN CHE
        {U'Ӎ', U'ӎ'}, // CYRILLIC CAPITAL LETTER EM WITH TAIL / CYRILLIC SMALL LETTER EM WITH TAIL
        {U'Ӑ', U'ӑ'}, // CYRILLIC CAPITAL LETTER A WITH BREVE / CYRILLIC SMALL LETTER A WITH BREVE
        {U'Ӓ', U'ӓ'}, // CYRILLIC CAPITAL LETTER A WITH DIAERESIS / CYRILLIC SMALL LETTER A WITH DIAERESIS
        {U'Ӕ', U'ӕ'}, // CYRILLIC CAPITAL LIGATURE A IE / CYRILLIC SMALL LIGATURE A IE
        {U'Ӗ', U'ӗ'}, // CYRILLIC CAPITAL LETTER IE WITH BREVE / CYRILLIC SMALL LETTER IE WITH BREVE
        {U'Ә', U'ә'}, // CYRILLIC CAPITAL LETTER SCHWA / CYRILLIC SMALL LETTER SCHWA
        {U'Ӛ', U'ӛ'}, // CYRILLIC CAPITAL LETTER SCHWA WITH DIAERESIS / CYRILLIC SMALL LETTER SCHWA WITH DIAERESIS
        {U'Ӝ', U'ӝ'}, // CYRILLIC CAPITAL LETTER ZHE WITH DIAERESIS / CYRILLIC SMALL LETTER ZHE WITH DIAERESIS
        {U'Ӟ', U'ӟ'}, // CYRILLIC CAPITAL LETTER ZE WITH DIAERESIS / CYRILLIC SMALL LETTER ZE WITH DIAERESIS
        {U'Ӡ', U'ӡ'}, // CYRILLIC CAPITAL LETTER ABKHASIAN DZE / CYRILLIC SMALL LETTER ABKHASIAN DZE
        {U'Ӣ', U'ӣ'}, // CYRILLIC CAPITAL LETTER I WITH MACRON / CYRILLIC SMALL LETTER I WITH MACRON
        {U'Ӥ', U'ӥ'}, // CYRILLIC CAPITAL LETTER I WITH DIAERESIS / CYRILLIC SMALL LETTER I WITH DIAERESIS
        {U'Ӧ', U'ӧ'}, // CYRILLIC CAPITAL LETTER O WITH DIAERESIS / CYRILLIC SMALL LETTER O WITH DIAERESIS
        {U'Ө', U'ө'}, // CYRILLIC CAPITAL LETTER BARRED O / CYRILLIC SMALL LETTER BARRED O
        {U'Ӫ', U'ӫ'}, // CYRILLIC CAPITAL LETTER BARRED O WITH DIAERESIS / CYRILLIC SMALL LETTER BARRED O WITH DIAERESIS
        {U'Ӭ', U'ӭ'}, // CYRILLIC CAPITAL LETTER E WITH DIAERESIS / CYRILLIC SMALL LETTER E WITH DIAERESIS
        {U'Ӯ', U'ӯ'}, // CYRILLIC CAPITAL LETTER U WITH MACRON / CYRILLIC SMALL LETTER U WITH MACRON
        {U'Ӱ', U'ӱ'}, // CYRILLIC CAPITAL LETTER U WITH DIAERESIS / CYRILLIC SMALL LETTER U WITH DIAERESIS
        {U'Ӳ', U'ӳ'}, // CYRILLIC CAPITAL LETTER U WITH DOUBLE ACUTE / CYRILLIC SMALL LETTER U WITH DOUBLE ACUTE
        {U'Ӵ', U'ӵ'}, // CYRILLIC CAPITAL LETTER CHE WITH DIAERESIS / CYRILLIC SMALL LETTER CHE WITH DIAERESIS
        {U'Ӷ', U'ӷ'}, // CYRILLIC CAPITAL LETTER GHE WITH DESCENDER / CYRILLIC SMALL LETTER GHE WITH DESCENDER
        {U'Ӹ', U'ӹ'}, // CYRILLIC CAPITAL LETTER YERU WITH DIAERESIS / CYRILLIC SMALL LETTER YERU WITH DIAERESIS
        {U'Ӻ', U'ӻ'}, // CYRILLIC CAPITAL LETTER GHE WITH STROKE AND HOOK / CYRILLIC SMALL LETTER GHE WITH STROKE AND HOOK
        {U'Ӽ', U'ӽ'}, // CYRILLIC CAPITAL LETTER HA WITH HOOK / CYRILLIC SMALL LETTER HA WITH HOOK
        {U'Ӿ', U'ӿ'}, // CYRILLIC CAPITAL LETTER HA WITH STROKE / CYRILLIC SMALL LETTER HA WITH STROKE
        {U'Ԁ', U'ԁ'}, // CYRILLIC CAPITAL LETTER KOMI DE / CYRILLIC SMALL LETTER KOMI DE
        {U'Ԃ', U'ԃ'}, // CYRILLIC CAPITAL LETTER KOMI DJE / CYRILLIC SMALL LETTER KOMI DJE
        {U'Ԅ', U'ԅ'}, // CYRILLIC CAPITAL LETTER KOMI ZJE / CYRILLIC SMALL LETTER KOMI ZJE
        {U'Ԇ', U'ԇ'}, // CYRILLIC CAPITAL LETTER KOMI DZJE / CYRILLIC SMALL LETTER KOMI DZJE
        {U'Ԉ', U'ԉ'}, // CYRILLIC CAPITAL LETTER KOMI LJE / CYRILLIC SMALL LETTER KOMI LJE
        {U'Ԋ', U'ԋ'}, // CYRILLIC CAPITAL LETTER KOMI NJE / CYRILLIC SMALL LETTER KOMI NJE
        {U'Ԍ', U'ԍ'}, // CYRILLIC CAPITAL LETTER KOMI SJE / CYRILLIC SMALL LETTER KOMI SJE
        {U'Ԏ', U'ԏ'}, // CYRILLIC CAPITAL LETTER KOMI TJE / CYRILLIC SMALL LETTER KOMI TJE
        {U'Ԑ', U'ԑ'}, // CYRILLIC CAPITAL LETTER REVERSED ZE / CYRILLIC SMALL LETTER REVERSED ZE
        {U'Ԓ', U'ԓ'}, // CYRILLIC CAPITAL LETTER EL WITH HOOK / CYRILLIC SMALL LETTER EL WITH HOOK
        {U'Ԕ', U'ԕ'}, // CYRILLIC CAPITAL LETTER LHA / CYRILLIC SMALL LETTER LHA
        {U'Ԗ', U'ԗ'}, // CYRILLIC CAPITAL LETTER RHA / CYRILLIC SMALL LETTER RHA
        {U'Ԙ', U'ԙ'}, // CYRILLIC CAPITAL LETTER YAE / CYRILLIC SMALL LETTER YAE
        {U'Ԛ', U'ԛ'}, // CYRILLIC CAPITAL LETTER QA / CYRILLIC SMALL LETTER QA
        {U'Ԝ', U'ԝ'}, // CYRILLIC CAPITAL LETTER WE / CYRILLIC SMALL LETTER WE
        {U'Ԟ', U'ԟ'}, // CYRILLIC CAPITAL LETTER ALEUT KA / CYRILLIC SMALL LETTER ALEUT KA
        {U'Ԡ', U'ԡ'}, // CYRILLIC CAPITAL LETTER EL WITH MIDDLE HOOK / CYRILLIC SMALL LETTER EL WITH MIDDLE HOOK
        {U'Ԣ', U'ԣ'}, // CYRILLIC CAPITAL LETTER EN WITH MIDDLE HOOK / CYRILLIC SMALL LETTER EN WITH MIDDLE HOOK
        {U'Ԥ', U'ԥ'}, // CYRILLIC CAPITAL LETTER PE WITH DESCENDER / CYRILLIC SMALL LETTER PE WITH DESCENDER
        {U'Ԧ', U'ԧ'}, // CYRILLIC CAPITAL LETTER SHHA WITH DESCENDER / CYRILLIC SMALL LETTER SHHA WITH DESCENDER
        {U'Ԩ', U'ԩ'}, // CYRILLIC CAPITAL LETTER EN WITH LEFT HOOK / CYRILLIC SMALL LETTER EN WITH LEFT HOOK
        {U'Ԫ', U'ԫ'}, // CYRILLIC CAPITAL LETTER DZZHE / CYRILLIC SMALL LETTER DZZHE
        {U'Ԭ', U'ԭ'}, // CYRILLIC CAPITAL LETTER DCHE / CYRILLIC SMALL LETTER DCHE
        {U'Ԯ', U'ԯ'}, // CYRILLIC CAPITAL LETTER EL WITH DESCENDER / CYRILLIC SMALL LETTER EL WITH DESCENDER
        {U'Ա', U'ա'}, // ARMENIAN CAPITAL LETTER AYB / ARMENIAN SMALL LETTER AYB
        {U'Բ', U'բ'}, // ARMENIAN CAPITAL LETTER BEN / ARMENIAN SMALL LETTER BEN
        {U'Գ', U'գ'}, // ARMENIAN CAPITAL LETTER GIM / ARMENIAN SMALL LETTER GIM
        {U'Դ', U'դ'}, // ARMENIAN CAPITAL LETTER DA / ARMENIAN SMALL LETTER DA
        {U'Ե', U'ե'}, // ARMENIAN CAPITAL LETTER ECH / ARMENIAN SMALL LETTER ECH
        {U'Զ', U'զ'}, // ARMENIAN CAPITAL LETTER ZA / ARMENIAN SMALL LETTER ZA
        {U'Է', U'է'}, // ARMENIAN CAPITAL LETTER EH / ARMENIAN SMALL LETTER EH
        {U'Ը', U'ը'}, // ARMENIAN CAPITAL LETTER ET / ARMENIAN SMALL LETTER ET
        {U'Թ', U'թ'}, // ARMENIAN CAPITAL LETTER TO / ARMENIAN SMALL LETTER TO
        {U'Ժ', U'ժ'}, // ARMENIAN CAPITAL LETTER ZHE / ARMENIAN SMALL LETTER ZHE
        {U'Ի', U'ի'}, // ARMENIAN CAPITAL LETTER INI / ARMENIAN SMALL LETTER INI
        {U'Լ', U'լ'}, // ARMENIAN CAPITAL LETTER LIWN / ARMENIAN SMALL LETTER LIWN
        {U'Խ', U'խ'}, // ARMENIAN CAPITAL LETTER XEH / ARMENIAN SMALL LETTER XEH
        {U'Ծ', U'ծ'}, // ARMENIAN CAPITAL LETTER CA / ARMENIAN SMALL LETTER CA
        {U'Կ', U'կ'}, // ARMENIAN CAPITAL LETTER KEN / ARMENIAN SMALL LETTER KEN
        {U'Հ', U'հ'}, // ARMENIAN CAPITAL LETTER HO / ARMENIAN SMALL LETTER HO
        {U'Ձ', U'ձ'}, // ARMENIAN CAPITAL LETTER JA / ARMENIAN SMALL LETTER JA
        {U'Ղ', U'ղ'}, // ARMENIAN CAPITAL LETTER GHAD / ARMENIAN SMALL LETTER GHAD
        {U'Ճ', U'ճ'}, // ARMENIAN CAPITAL LETTER CHEH / ARMENIAN SMALL LETTER CHEH
        {U'Մ', U'մ'}, // ARMENIAN CAPITAL LETTER MEN / ARMENIAN SMALL LETTER MEN
        {U'Յ', U'յ'}, // ARMENIAN CAPITAL LETTER YI / ARMENIAN SMALL LETTER YI
        {U'Ն', U'ն'}, // ARMENIAN CAPITAL LETTER NOW / ARMENIAN SMALL LETTER NOW
        {U'Շ', U'շ'}, // ARMENIAN CAPITAL LETTER SHA / ARMENIAN SMALL LETTER SHA
        {U'Ո', U'ո'}, // ARMENIAN CAPITAL LETTER VO / ARMENIAN SMALL LETTER VO
        {U'Չ', U'չ'}, // ARMENIAN CAPITAL LETTER CHA / ARMENIAN SMALL LETTER CHA
        {U'Պ', U'պ'}, // ARMENIAN CAPITAL LETTER PEH / ARMENIAN SMALL LETTER PEH
        {U'Ջ', U'ջ'}, // ARMENIAN CAPITAL LETTER JHEH / ARMENIAN SMALL LETTER JHEH
        {U'Ռ', U'ռ'}, // ARMENIAN CAPITAL LETTER RA / ARMENIAN SMALL LETTER RA
        {U'Ս', U'ս'}, // ARMENIAN CAPITAL LETTER SEH / ARMENIAN SMALL LETTER SEH
        {U'Վ', U'վ'}, // ARMENIAN CAPITAL LETTER VEW / ARMENIAN SMALL LETTER VEW
        {U'Տ', U'տ'}, // ARMENIAN CAPITAL LETTER TIWN / ARMENIAN SMALL LETTER TIWN
        {U'Ր', U'ր'}, // ARMENIAN CAPITAL LETTER REH / ARMENIAN SMALL LETTER REH
        {U'Ց', U'ց'}, // ARMENIAN CAPITAL LETTER CO / ARMENIAN SMALL LETTER CO
        {U'Ւ', U'ւ'}, // ARMENIAN CAPITAL LETTER YIWN / ARMENIAN SMALL LETTER YIWN
        {U'Փ', U'փ'}, // ARMENIAN CAPITAL LETTER PIWR / ARMENIAN SMALL LETTER PIWR
        {U'Ք', U'ք'}, // ARMENIAN CAPITAL LETTER KEH / ARMENIAN SMALL LETTER KEH
        {U'Օ', U'օ'}, // ARMENIAN CAPITAL LETTER OH / ARMENIAN SMALL LETTER OH
        {U'Ֆ', U'ֆ'}, // ARMENIAN CAPITAL LETTER FEH / ARMENIAN SMALL LETTER FEH
        {U'Ⴀ', U'ⴀ'}, // GEORGIAN CAPITAL LETTER AN / GEORGIAN SMALL LETTER AN
        {U'Ⴁ', U'ⴁ'}, // GEORGIAN CAPITAL LETTER BAN / GEORGIAN SMALL LETTER BAN
        {U'Ⴂ', U'ⴂ'}, // GEORGIAN CAPITAL LETTER GAN / GEORGIAN SMALL LETTER GAN
        {U'Ⴃ', U'ⴃ'}, // GEORGIAN CAPITAL LETTER DON / GEORGIAN SMALL LETTER DON
        {U'Ⴄ', U'ⴄ'}, // GEORGIAN CAPITAL LETTER EN / GEORGIAN SMALL LETTER EN
        {U'Ⴅ', U'ⴅ'}, // GEORGIAN CAPITAL LETTER VIN / GEORGIAN SMALL LETTER VIN
        {U'Ⴆ', U'ⴆ'}, // GEORGIAN CAPITAL LETTER ZEN / GEORGIAN SMALL LETTER ZEN
        {U'Ⴇ', U'ⴇ'}, // GEORGIAN CAPITAL LETTER TAN / GEORGIAN SMALL LETTER TAN
        {U'Ⴈ', U'ⴈ'}, // GEORGIAN CAPITAL LETTER IN / GEORGIAN SMALL LETTER IN
        {U'Ⴉ', U'ⴉ'}, // GEORGIAN CAPITAL LETTER KAN / GEORGIAN SMALL LETTER KAN
        {U'Ⴊ', U'ⴊ'}, // GEORGIAN CAPITAL LETTER LAS / GEORGIAN SMALL LETTER LAS
        {U'Ⴋ', U'ⴋ'}, // GEORGIAN CAPITAL LETTER MAN / GEORGIAN SMALL LETTER MAN
        {U'Ⴌ', U'ⴌ'}, // GEORGIAN CAPITAL LETTER NAR / GEORGIAN SMALL LETTER NAR
        {U'Ⴍ', U'ⴍ'}, // GEORGIAN CAPITAL LETTER ON / GEORGIAN SMALL LETTER ON
        {U'Ⴎ', U'ⴎ'}, // GEORGIAN CAPITAL LETTER PAR / GEORGIAN SMALL LETTER PAR
        {U'Ⴏ', U'ⴏ'}, // GEORGIAN CAPITAL LETTER ZHAR / GEORGIAN SMALL LETTER ZHAR
        {U'Ⴐ', U'ⴐ'}, // GEORGIAN CAPITAL LETTER RAE / GEORGIAN SMALL LETTER RAE
        {U'Ⴑ', U'ⴑ'}, // GEORGIAN CAPITAL LETTER SAN / GEORGIAN SMALL LETTER SAN
        {U'Ⴒ', U'ⴒ'}, // GEORGIAN CAPITAL LETTER TAR / GEORGIAN SMALL LETTER TAR
        {U'Ⴓ', U'ⴓ'}, // GEORGIAN CAPITAL LETTER UN / GEORGIAN SMALL LETTER UN
        {U'Ⴔ', U'ⴔ'}, // GEORGIAN CAPITAL LETTER PHAR / GEORGIAN SMALL LETTER PHAR
        {U'Ⴕ', U'ⴕ'}, // GEORGIAN CAPITAL LETTER KHAR / GEORGIAN SMALL LETTER KHAR
        {U'Ⴖ', U'ⴖ'}, // GEORGIAN CAPITAL LETTER GHAN / GEORGIAN SMALL LETTER GHAN
        {U'Ⴗ', U'ⴗ'}, // GEORGIAN CAPITAL LETTER QAR / GEORGIAN SMALL LETTER QAR
        {U'Ⴘ', U'ⴘ'}, // GEORGIAN CAPITAL LETTER SHIN / GEORGIAN SMALL LETTER SHIN
        {U'Ⴙ', U'ⴙ'}, // GEORGIAN CAPITAL LETTER CHIN / GEORGIAN SMALL LETTER CHIN
        {U'Ⴚ', U'ⴚ'}, // GEORGIAN CAPITAL LETTER CAN / GEORGIAN SMALL LETTER CAN
        {U'Ⴛ', U'ⴛ'}, // GEORGIAN CAPITAL LETTER JIL / GEORGIAN SMALL LETTER JIL
        {U'Ⴜ', U'ⴜ'}, // GEORGIAN CAPITAL LETTER CIL / GEORGIAN SMALL LETTER CIL
        {U'Ⴝ', U'ⴝ'}, // GEORGIAN CAPITAL LETTER CHAR / GEORGIAN SMALL LETTER CHAR
        {U'Ⴞ', U'ⴞ'}, // GEORGIAN CAPITAL LETTER XAN / GEORGIAN SMALL LETTER XAN
        {U'Ⴟ', U'ⴟ'}, // GEORGIAN CAPITAL LETTER JHAN / GEORGIAN SMALL LETTER JHAN
        {U'Ⴠ', U'ⴠ'}, // GEORGIAN CAPITAL LETTER HAE / GEORGIAN SMALL LETTER HAE
        {U'Ⴡ', U'ⴡ'}, // GEORGIAN CAPITAL LETTER HE / GEORGIAN SMALL LETTER HE
        {U'Ⴢ', U'ⴢ'}, // GEORGIAN CAPITAL LETTER HIE / GEORGIAN SMALL LETTER HIE
        {U'Ⴣ', U'ⴣ'}, // GEORGIAN CAPITAL LETTER WE / GEORGIAN SMALL LETTER WE
        {U'Ⴤ', U'ⴤ'}, // GEORGIAN CAPITAL LETTER HAR / GEORGIAN SMALL LETTER HAR
        {U'Ⴥ', U'ⴥ'}, // GEORGIAN CAPITAL LETTER HOE / GEORGIAN SMALL LETTER HOE
        {U'Ⴧ', U'ⴧ'}, // GEORGIAN CAPITAL LETTER YN / GEORGIAN SMALL LETTER YN
        {U'Ⴭ', U'ⴭ'}, // GEORGIAN CAPITAL LETTER AEN / GEORGIAN SMALL LETTER AEN
        {U'Ḁ', U'ḁ'}, // LATIN CAPITAL LETTER A WITH RING BELOW / LATIN SMALL LETTER A WITH RING BELOW
        {U'Ḃ', U'ḃ'}, // LATIN CAPITAL LETTER B WITH DOT ABOVE / LATIN SMALL LETTER B WITH DOT ABOVE
        {U'Ḅ', U'ḅ'}, // LATIN CAPITAL LETTER B WITH DOT BELOW / LATIN SMALL LETTER B WITH DOT BELOW
        {U'Ḇ', U'ḇ'}, // LATIN CAPITAL LETTER B WITH LINE BELOW / LATIN SMALL LETTER B WITH LINE BELOW
        {U'Ḉ', U'ḉ'}, // LATIN CAPITAL LETTER C WITH CEDILLA AND ACUTE / LATIN SMALL LETTER C WITH CEDILLA AND ACUTE
        {U'Ḋ', U'ḋ'}, // LATIN CAPITAL LETTER D WITH DOT ABOVE / LATIN SMALL LETTER D WITH DOT ABOVE
        {U'Ḍ', U'ḍ'}, // LATIN CAPITAL LETTER D WITH DOT BELOW / LATIN SMALL LETTER D WITH DOT BELOW
        {U'Ḏ', U'ḏ'}, // LATIN CAPITAL LETTER D WITH LINE BELOW / LATIN SMALL LETTER D WITH LINE BELOW
        {U'Ḑ', U'ḑ'}, // LATIN CAPITAL LETTER D WITH CEDILLA / LATIN SMALL LETTER D WITH CEDILLA
        {U'Ḓ', U'ḓ'}, // LATIN CAPITAL LETTER D WITH CIRCUMFLEX BELOW / LATIN SMALL LETTER D WITH CIRCUMFLEX BELOW
        {U'Ḕ', U'ḕ'}, // LATIN CAPITAL LETTER E WITH MACRON AND GRAVE / LATIN SMALL LETTER E WITH MACRON AND GRAVE
        {U'Ḗ', U'ḗ'}, // LATIN CAPITAL LETTER E WITH MACRON AND ACUTE / LATIN SMALL LETTER E WITH MACRON AND ACUTE
        {U'Ḙ', U'ḙ'}, // LATIN CAPITAL LETTER E WITH CIRCUMFLEX BELOW / LATIN SMALL LETTER E WITH CIRCUMFLEX BELOW
        {U'Ḛ', U'ḛ'}, // LATIN CAPITAL LETTER E WITH TILDE BELOW / LATIN SMALL LETTER E WITH TILDE BELOW
        {U'Ḝ', U'ḝ'}, // LATIN CAPITAL LETTER E WITH CEDILLA AND BREVE / LATIN SMALL LETTER E WITH CEDILLA AND BREVE
        {U'Ḟ', U'ḟ'}, // LATIN CAPITAL LETTER F WITH DOT ABOVE / LATIN SMALL LETTER F WITH DOT ABOVE
        {U'Ḡ', U'ḡ'}, // LATIN CAPITAL LETTER G WITH MACRON / LATIN SMALL LETTER G WITH MACRON
        {U'Ḣ', U'ḣ'}, // LATIN CAPITAL LETTER H WITH DOT ABOVE / LATIN SMALL LETTER H WITH DOT ABOVE
        {U'Ḥ', U'ḥ'}, // LATIN CAPITAL LETTER H WITH DOT BELOW / LATIN SMALL LETTER H WITH DOT BELOW
        {U'Ḧ', U'ḧ'}, // LATIN CAPITAL LETTER H WITH DIAERESIS / LATIN SMALL LETTER H WITH DIAERESIS
        {U'Ḩ', U'ḩ'}, // LATIN CAPITAL LETTER H WITH CEDILLA / LATIN SMALL LETTER H WITH CEDILLA
        {U'Ḫ', U'ḫ'}, // LATIN CAPITAL LETTER H WITH BREVE BELOW / LATIN SMALL LETTER H WITH BREVE BELOW
        {U'Ḭ', U'ḭ'}, // LATIN CAPITAL LETTER I WITH TILDE BELOW / LATIN SMALL LETTER I WITH TILDE BELOW
        {U'Ḯ', U'ḯ'}, // LATIN CAPITAL LETTER I WITH DIAERESIS AND ACUTE / LATIN SMALL LETTER I WITH DIAERESIS AND ACUTE
        {U'Ḱ', U'ḱ'}, // LATIN CAPITAL LETTER K WITH ACUTE / LATIN SMALL LETTER K WITH ACUTE
        {U'Ḳ', U'ḳ'}, // LATIN CAPITAL LETTER K WITH DOT BELOW / LATIN SMALL LETTER K WITH DOT BELOW
        {U'Ḵ', U'ḵ'}, // LATIN CAPITAL LETTER K WITH LINE BELOW / LATIN SMALL LETTER K WITH LINE BELOW
        {U'Ḷ', U'ḷ'}, // LATIN CAPITAL LETTER L WITH DOT BELOW / LATIN SMALL LETTER L WITH DOT BELOW
        {U'Ḹ', U'ḹ'}, // LATIN CAPITAL LETTER L WITH DOT BELOW AND MACRON / LATIN SMALL LETTER L WITH DOT BELOW AND MACRON
        {U'Ḻ', U'ḻ'}, // LATIN CAPITAL LETTER L WITH LINE BELOW / LATIN SMALL LETTER L WITH LINE BELOW
        {U'Ḽ', U'ḽ'}, // LATIN CAPITAL LETTER L WITH CIRCUMFLEX BELOW / LATIN SMALL LETTER L WITH CIRCUMFLEX BELOW
        {U'Ḿ', U'ḿ'}, // LATIN CAPITAL LETTER M WITH ACUTE / LATIN SMALL LETTER M WITH ACUTE
        {U'Ṁ', U'ṁ'}, // LATIN CAPITAL LETTER M WITH DOT ABOVE / LATIN SMALL LETTER M WITH DOT ABOVE
        {U'Ṃ', U'ṃ'}, // LATIN CAPITAL LETTER M WITH DOT BELOW / LATIN SMALL LETTER M WITH DOT BELOW
        {U'Ṅ', U'ṅ'}, // LATIN CAPITAL LETTER N WITH DOT ABOVE / LATIN SMALL LETTER N WITH DOT ABOVE
        {U'Ṇ', U'ṇ'}, // LATIN CAPITAL LETTER N WITH DOT BELOW / LATIN SMALL LETTER N WITH DOT BELOW
        {U'Ṉ', U'ṉ'}, // LATIN CAPITAL LETTER N WITH LINE BELOW / LATIN SMALL LETTER N WITH LINE BELOW
        {U'Ṋ', U'ṋ'}, // LATIN CAPITAL LETTER N WITH CIRCUMFLEX BELOW / LATIN SMALL LETTER N WITH CIRCUMFLEX BELOW
        {U'Ṍ', U'ṍ'}, // LATIN CAPITAL LETTER O WITH TILDE AND ACUTE / LATIN SMALL LETTER O WITH TILDE AND ACUTE
        {U'Ṏ', U'ṏ'}, // LATIN CAPITAL LETTER O WITH TILDE AND DIAERESIS / LATIN SMALL LETTER O WITH TILDE AND DIAERESIS
        {U'Ṑ', U'ṑ'}, // LATIN CAPITAL LETTER O WITH MACRON AND GRAVE / LATIN SMALL LETTER O WITH MACRON AND GRAVE
        {U'Ṓ', U'ṓ'}, // LATIN CAPITAL LETTER O WITH MACRON AND ACUTE / LATIN SMALL LETTER O WITH MACRON AND ACUTE
        {U'Ṕ', U'ṕ'}, // LATIN CAPITAL LETTER P WITH ACUTE / LATIN SMALL LETTER P WITH ACUTE
        {U'Ṗ', U'ṗ'}, // LATIN CAPITAL LETTER P WITH DOT ABOVE / LATIN SMALL LETTER P WITH DOT ABOVE
        {U'Ṙ', U'ṙ'}, // LATIN CAPITAL LETTER R WITH DOT ABOVE / LATIN SMALL LETTER R WITH DOT ABOVE
        {U'Ṛ', U'ṛ'}, // LATIN CAPITAL LETTER R WITH DOT BELOW / LATIN SMALL LETTER R WITH DOT BELOW
        {U'Ṝ', U'ṝ'}, // LATIN CAPITAL LETTER R WITH DOT BELOW AND MACRON / LATIN SMALL LETTER R WITH DOT BELOW AND MACRON
        {U'Ṟ', U'ṟ'}, // LATIN CAPITAL LETTER R WITH LINE BELOW / LATIN SMALL LETTER R WITH LINE BELOW
        {U'Ṡ', U'ṡ'}, // LATIN CAPITAL LETTER S WITH DOT ABOVE / LATIN SMALL LETTER S WITH DOT ABOVE
        {U'Ṣ', U'ṣ'}, // LATIN CAPITAL LETTER S WITH DOT BELOW / LATIN SMALL LETTER S WITH DOT BELOW
        {U'Ṥ', U'ṥ'}, // LATIN CAPITAL LETTER S WITH ACUTE AND DOT ABOVE / LATIN SMALL LETTER S WITH ACUTE AND DOT ABOVE
        {U'Ṧ', U'ṧ'}, // LATIN CAPITAL LETTER S WITH CARON AND DOT ABOVE / LATIN SMALL LETTER S WITH CARON AND DOT ABOVE
        {U'Ṩ', U'ṩ'}, // LATIN CAPITAL LETTER S WITH DOT BELOW AND DOT ABOVE / LATIN SMALL LETTER S WITH DOT BELOW AND DOT ABOVE
        {U'Ṫ', U'ṫ'}, // LATIN CAPITAL LETTER T WITH DOT ABOVE / LATIN SMALL LETTER T WITH DOT ABOVE
        {U'Ṭ', U'ṭ'}, // LATIN CAPITAL LETTER T WITH DOT BELOW / LATIN SMALL LETTER T WITH DOT BELOW
        {U'Ṯ', U'ṯ'}, // LATIN CAPITAL LETTER T WITH LINE BELOW / LATIN SMALL LETTER T WITH LINE BELOW
        {U'Ṱ', U'ṱ'}, // LATIN CAPITAL LETTER T WITH CIRCUMFLEX BELOW / LATIN SMALL LETTER T WITH CIRCUMFLEX BELOW
        {U'Ṳ', U'ṳ'}, // LATIN CAPITAL LETTER U WITH DIAERESIS BELOW / LATIN SMALL LETTER U WITH DIAERESIS BELOW
        {U'Ṵ', U'ṵ'}, // LATIN CAPITAL LETTER U WITH TILDE BELOW / LATIN SMALL LETTER U WITH TILDE BELOW
        {U'Ṷ', U'ṷ'}, // LATIN CAPITAL LETTER U WITH CIRCUMFLEX BELOW / LATIN SMALL LETTER U WITH CIRCUMFLEX BELOW
        {U'Ṹ', U'ṹ'}, // LATIN CAPITAL LETTER U WITH TILDE AND ACUTE / LATIN SMALL LETTER U WITH TILDE AND ACUTE
        {U'Ṻ', U'ṻ'}, // LATIN CAPITAL LETTER U WITH MACRON AND DIAERESIS / LATIN SMALL LETTER U WITH MACRON AND DIAERESIS
        {U'Ṽ', U'ṽ'}, // LATIN CAPITAL LETTER V WITH TILDE / LATIN SMALL LETTER V WITH TILDE
        {U'Ṿ', U'ṿ'}, // LATIN CAPITAL LETTER V WITH DOT BELOW / LATIN SMALL LETTER V WITH DOT BELOW
        {U'Ẁ', U'ẁ'}, // LATIN CAPITAL LETTER W WITH GRAVE / LATIN SMALL LETTER W WITH GRAVE
        {U'Ẃ', U'ẃ'}, // LATIN CAPITAL LETTER W WITH ACUTE / LATIN SMALL LETTER W WITH ACUTE
        {U'Ẅ', U'ẅ'}, // LATIN CAPITAL LETTER W WITH DIAERESIS / LATIN SMALL LETTER W WITH DIAERESIS
        {U'Ẇ', U'ẇ'}, // LATIN CAPITAL LETTER W WITH DOT ABOVE / LATIN SMALL LETTER W WITH DOT ABOVE
        {U'Ẉ', U'ẉ'}, // LATIN CAPITAL LETTER W WITH DOT BELOW / LATIN SMALL LETTER W WITH DOT BELOW
        {U'Ẋ', U'ẋ'}, // LATIN CAPITAL LETTER X WITH DOT ABOVE / LATIN SMALL LETTER X WITH DOT ABOVE
        {U'Ẍ', U'ẍ'}, // LATIN CAPITAL LETTER X WITH DIAERESIS / LATIN SMALL LETTER X WITH DIAERESIS
        {U'Ẏ', U'ẏ'}, // LATIN CAPITAL LETTER Y WITH DOT ABOVE / LATIN SMALL LETTER Y WITH DOT ABOVE
        {U'Ẑ', U'ẑ'}, // LATIN CAPITAL LETTER Z WITH CIRCUMFLEX / LATIN SMALL LETTER Z WITH CIRCUMFLEX
        {U'Ẓ', U'ẓ'}, // LATIN CAPITAL LETTER Z WITH DOT BELOW / LATIN SMALL LETTER Z WITH DOT BELOW
        {U'Ẕ', U'ẕ'}, // LATIN CAPITAL LETTER Z WITH LINE BELOW / LATIN SMALL LETTER Z WITH LINE BELOW
        {U'ẞ', U'ß'}, // LATIN CAPITAL LETTER SHARP S / LATIN SMALL LETTER SHARP S
        {U'Ạ', U'ạ'}, // LATIN CAPITAL LETTER A WITH DOT BELOW / LATIN SMALL LETTER A WITH DOT BELOW
        {U'Ả', U'ả'}, // LATIN CAPITAL LETTER A WITH HOOK ABOVE / LATIN SMALL LETTER A WITH HOOK ABOVE
        {U'Ấ', U'ấ'}, // LATIN CAPITAL LETTER A WITH CIRCUMFLEX AND ACUTE / LATIN SMALL LETTER A WITH CIRCUMFLEX AND ACUTE
        {U'Ầ', U'ầ'}, // LATIN CAPITAL LETTER A WITH CIRCUMFLEX AND GRAVE / LATIN SMALL LETTER A WITH CIRCUMFLEX AND GRAVE
        {U'Ẩ', U'ẩ'}, // LATIN CAPITAL LETTER A WITH CIRCUMFLEX AND HOOK ABOVE / LATIN SMALL LETTER A WITH CIRCUMFLEX AND HOOK ABOVE
        {U'Ẫ', U'ẫ'}, // LATIN CAPITAL LETTER A WITH CIRCUMFLEX AND TILDE / LATIN SMALL LETTER A WITH CIRCUMFLEX AND TILDE
        {U'Ậ', U'ậ'}, // LATIN CAPITAL LETTER A WITH CIRCUMFLEX AND DOT BELOW / LATIN SMALL LETTER A WITH CIRCUMFLEX AND DOT BELOW
        {U'Ắ', U'ắ'}, // LATIN CAPITAL LETTER A WITH BREVE AND ACUTE / LATIN SMALL LETTER A WITH BREVE AND ACUTE
        {U'Ằ', U'ằ'}, // LATIN CAPITAL LETTER A WITH BREVE AND GRAVE / LATIN SMALL LETTER A WITH BREVE AND GRAVE
        {U'Ẳ', U'ẳ'}, // LATIN CAPITAL LETTER A WITH BREVE AND HOOK ABOVE / LATIN SMALL LETTER A WITH BREVE AND HOOK ABOVE
        {U'Ẵ', U'ẵ'}, // LATIN CAPITAL LETTER A WITH BREVE AND TILDE / LATIN SMALL LETTER A WITH BREVE AND TILDE
        {U'Ặ', U'ặ'}, // LATIN CAPITAL LETTER A WITH BREVE AND DOT BELOW / LATIN SMALL LETTER A WITH BREVE AND DOT BELOW
        {U'Ẹ', U'ẹ'}, // LATIN CAPITAL LETTER E WITH DOT BELOW / LATIN SMALL LETTER E WITH DOT BELOW
        {U'Ẻ', U'ẻ'}, // LATIN CAPITAL LETTER E WITH HOOK ABOVE / LATIN SMALL LETTER E WITH HOOK ABOVE
        {U'Ẽ', U'ẽ'}, // LATIN CAPITAL LETTER E WITH TILDE / LATIN SMALL LETTER E WITH TILDE
        {U'Ế', U'ế'}, // LATIN CAPITAL LETTER E WITH CIRCUMFLEX AND ACUTE / LATIN SMALL LETTER E WITH CIRCUMFLEX AND ACUTE
        {U'Ề', U'ề'}, // LATIN CAPITAL LETTER E WITH CIRCUMFLEX AND GRAVE / LATIN SMALL LETTER E WITH CIRCUMFLEX AND GRAVE
        {U'Ể', U'ể'}, // LATIN CAPITAL LETTER E WITH CIRCUMFLEX AND HOOK ABOVE / LATIN SMALL LETTER E WITH CIRCUMFLEX AND HOOK ABOVE
        {U'Ễ', U'ễ'}, // LATIN CAPITAL LETTER E WITH CIRCUMFLEX AND TILDE / LATIN SMALL LETTER E WITH CIRCUMFLEX AND TILDE
        {U'Ệ', U'ệ'}, // LATIN CAPITAL LETTER E WITH CIRCUMFLEX AND DOT BELOW / LATIN SMALL LETTER E WITH CIRCUMFLEX AND DOT BELOW
        {U'Ỉ', U'ỉ'}, // LATIN CAPITAL LETTER I WITH HOOK ABOVE / LATIN SMALL LETTER I WITH HOOK ABOVE
        {U'Ị', U'ị'}, // LATIN CAPITAL LETTER I WITH DOT BELOW / LATIN SMALL LETTER I WITH DOT BELOW
        {U'Ọ', U'ọ'}, // LATIN CAPITAL LETTER O WITH DOT BELOW / LATIN SMALL LETTER O WITH DOT BELOW
        {U'Ỏ', U'ỏ'}, // LATIN CAPITAL LETTER O WITH HOOK ABOVE / LATIN SMALL LETTER O WITH HOOK ABOVE
        {U'Ố', U'ố'}, // LATIN CAPITAL LETTER O WITH CIRCUMFLEX AND ACUTE / LATIN SMALL LETTER O WITH CIRCUMFLEX AND ACUTE
        {U'Ồ', U'ồ'}, // LATIN CAPITAL LETTER O WITH CIRCUMFLEX AND GRAVE / LATIN SMALL LETTER O WITH CIRCUMFLEX AND GRAVE
        {U'Ổ', U'ổ'}, // LATIN CAPITAL LETTER O WITH CIRCUMFLEX AND HOOK ABOVE / LATIN SMALL LETTER O WITH CIRCUMFLEX AND HOOK ABOVE
        {U'Ỗ', U'ỗ'}, // LATIN CAPITAL LETTER O WITH CIRCUMFLEX AND TILDE / LATIN SMALL LETTER O WITH CIRCUMFLEX AND TILDE
        {U'Ộ', U'ộ'}, // LATIN CAPITAL LETTER O WITH CIRCUMFLEX AND DOT BELOW / LATIN SMALL LETTER O WITH CIRCUMFLEX AND DOT BELOW
        {U'Ớ', U'ớ'}, // LATIN CAPITAL LETTER O WITH HORN AND ACUTE / LATIN SMALL LETTER O WITH HORN AND ACUTE
        {U'Ờ', U'ờ'}, // LATIN CAPITAL LETTER O WITH HORN AND GRAVE / LATIN SMALL LETTER O WITH HORN AND GRAVE
        {U'Ở', U'ở'}, // LATIN CAPITAL LETTER O WITH HORN AND HOOK ABOVE / LATIN SMALL LETTER O WITH HORN AND HOOK ABOVE
        {U'Ỡ', U'ỡ'}, // LATIN CAPITAL LETTER O WITH HORN AND TILDE / LATIN SMALL LETTER O WITH HORN AND TILDE
        {U'Ợ', U'ợ'}, // LATIN CAPITAL LETTER O WITH HORN AND DOT BELOW / LATIN SMALL LETTER O WITH HORN AND DOT BELOW
        {U'Ụ', U'ụ'}, // LATIN CAPITAL LETTER U WITH DOT BELOW / LATIN SMALL LETTER U WITH DOT BELOW
        {U'Ủ', U'ủ'}, // LATIN CAPITAL LETTER U WITH HOOK ABOVE / LATIN SMALL LETTER U WITH HOOK ABOVE
        {U'Ứ', U'ứ'}, // LATIN CAPITAL LETTER U WITH HORN AND ACUTE / LATIN SMALL LETTER U WITH HORN AND ACUTE
        {U'Ừ', U'ừ'}, // LATIN CAPITAL LETTER U WITH HORN AND GRAVE / LATIN SMALL LETTER U WITH HORN AND GRAVE
        {U'Ử', U'ử'}, // LATIN CAPITAL LETTER U WITH HORN AND HOOK ABOVE / LATIN SMALL LETTER U WITH HORN AND HOOK ABOVE
        {U'Ữ', U'ữ'}, // LATIN CAPITAL LETTER U WITH HORN AND TILDE / LATIN SMALL LETTER U WITH HORN AND TILDE
        {U'Ự', U'ự'}, // LATIN CAPITAL LETTER U WITH HORN AND DOT BELOW / LATIN SMALL LETTER U WITH HORN AND DOT BELOW
        {U'Ỳ', U'ỳ'}, // LATIN CAPITAL LETTER Y WITH GRAVE / LATIN SMALL LETTER Y WITH GRAVE
        {U'Ỵ', U'ỵ'}, // LATIN CAPITAL LETTER Y WITH DOT BELOW / LATIN SMALL LETTER Y WITH DOT BELOW
        {U'Ỷ', U'ỷ'}, // LATIN CAPITAL LETTER Y WITH HOOK ABOVE / LATIN SMALL LETTER Y WITH HOOK ABOVE
        {U'Ỹ', U'ỹ'}, // LATIN CAPITAL LETTER Y WITH TILDE / LATIN SMALL LETTER Y WITH TILDE
        {U'Ỻ', U'ỻ'}, // LATIN CAPITAL LETTER MIDDLE-WELSH LL / LATIN SMALL LETTER MIDDLE-WELSH LL
        {U'Ỽ', U'ỽ'}, // LATIN CAPITAL LETTER MIDDLE-WELSH V / LATIN SMALL LETTER MIDDLE-WELSH V
        {U'Ỿ', U'ỿ'}, // LATIN CAPITAL LETTER Y WITH LOOP / LATIN SMALL LETTER Y WITH LOOP
        {U'Ἀ', U'ἀ'}, // GREEK CAPITAL LETTER ALPHA WITH PSILI / GREEK SMALL LETTER ALPHA WITH PSILI
        {U'Ἁ', U'ἁ'}, // GREEK CAPITAL LETTER ALPHA WITH DASIA / GREEK SMALL LETTER ALPHA WITH DASIA
        {U'Ἂ', U'ἂ'}, // GREEK CAPITAL LETTER ALPHA WITH PSILI AND VARIA / GREEK SMALL LETTER ALPHA WITH PSILI AND VARIA
        {U'Ἃ', U'ἃ'}, // GREEK CAPITAL LETTER ALPHA WITH DASIA AND VARIA / GREEK SMALL LETTER ALPHA WITH DASIA AND VARIA
        {U'Ἄ', U'ἄ'}, // GREEK CAPITAL LETTER ALPHA WITH PSILI AND OXIA / GREEK SMALL LETTER ALPHA WITH PSILI AND OXIA
        {U'Ἅ', U'ἅ'}, // GREEK CAPITAL LETTER ALPHA WITH DASIA AND OXIA / GREEK SMALL LETTER ALPHA WITH DASIA AND OXIA
        {U'Ἆ', U'ἆ'}, // GREEK CAPITAL LETTER ALPHA WITH PSILI AND PERISPOMENI / GREEK SMALL LETTER ALPHA WITH PSILI AND PERISPOMENI
        {U'Ἇ', U'ἇ'}, // GREEK CAPITAL LETTER ALPHA WITH DASIA AND PERISPOMENI / GREEK SMALL LETTER ALPHA WITH DASIA AND PERISPOMENI
        {U'Ἐ', U'ἐ'}, // GREEK CAPITAL LETTER EPSILON WITH PSILI / GREEK SMALL LETTER EPSILON WITH PSILI
        {U'Ἑ', U'ἑ'}, // GREEK CAPITAL LETTER EPSILON WITH DASIA / GREEK SMALL LETTER EPSILON WITH DASIA
        {U'Ἒ', U'ἒ'}, // GREEK CAPITAL LETTER EPSILON WITH PSILI AND VARIA / GREEK SMALL LETTER EPSILON WITH PSILI AND VARIA
        {U'Ἓ', U'ἓ'}, // GREEK CAPITAL LETTER EPSILON WITH DASIA AND VARIA / GREEK SMALL LETTER EPSILON WITH DASIA AND VARIA
        {U'Ἔ', U'ἔ'}, // GREEK CAPITAL LETTER EPSILON WITH PSILI AND OXIA / GREEK SMALL LETTER EPSILON WITH PSILI AND OXIA
        {U'Ἕ', U'ἕ'}, // GREEK CAPITAL LETTER EPSILON WITH DASIA AND OXIA / GREEK SMALL LETTER EPSILON WITH DASIA AND OXIA
        {U'Ἠ', U'ἠ'}, // GREEK CAPITAL LETTER ETA WITH PSILI / GREEK SMALL LETTER ETA WITH PSILI
        {U'Ἡ', U'ἡ'}, // GREEK CAPITAL LETTER ETA WITH DASIA / GREEK SMALL LETTER ETA WITH DASIA
        {U'Ἢ', U'ἢ'}, // GREEK CAPITAL LETTER ETA WITH PSILI AND VARIA / GREEK SMALL LETTER ETA WITH PSILI AND VARIA
        {U'Ἣ', U'ἣ'}, // GREEK CAPITAL LETTER ETA WITH DASIA AND VARIA / GREEK SMALL LETTER ETA WITH DASIA AND VARIA
        {U'Ἤ', U'ἤ'}, // GREEK CAPITAL LETTER ETA WITH PSILI AND OXIA / GREEK SMALL LETTER ETA WITH PSILI AND OXIA
        {U'Ἥ', U'ἥ'}, // GREEK CAPITAL LETTER ETA WITH DASIA AND OXIA / GREEK SMALL LETTER ETA WITH DASIA AND OXIA
        {U'Ἦ', U'ἦ'}, // GREEK CAPITAL LETTER ETA WITH PSILI AND PERISPOMENI / GREEK SMALL LETTER ETA WITH PSILI AND PERISPOMENI
        {U'Ἧ', U'ἧ'}, // GREEK CAPITAL LETTER ETA WITH DASIA AND PERISPOMENI / GREEK SMALL LETTER ETA WITH DASIA AND PERISPOMENI
        {U'Ἰ', U'ἰ'}, // GREEK CAPITAL LETTER IOTA WITH PSILI / GREEK SMALL LETTER IOTA WITH PSILI
        {U'Ἱ', U'ἱ'}, // GREEK CAPITAL LETTER IOTA WITH DASIA / GREEK SMALL LETTER IOTA WITH DASIA
        {U'Ἲ', U'ἲ'}, // GREEK CAPITAL LETTER IOTA WITH PSILI AND VARIA / GREEK SMALL LETTER IOTA WITH PSILI AND VARIA
        {U'Ἳ', U'ἳ'}, // GREEK CAPITAL LETTER IOTA WITH DASIA AND VARIA / GREEK SMALL LETTER IOTA WITH DASIA AND VARIA
        {U'Ἴ', U'ἴ'}, // GREEK CAPITAL LETTER IOTA WITH PSILI AND OXIA / GREEK SMALL LETTER IOTA WITH PSILI AND OXIA
        {U'Ἵ', U'ἵ'}, // GREEK CAPITAL LETTER IOTA WITH DASIA AND OXIA / GREEK SMALL LETTER IOTA WITH DASIA AND OXIA
        {U'Ἶ', U'ἶ'}, // GREEK CAPITAL LETTER IOTA WITH PSILI AND PERISPOMENI / GREEK SMALL LETTER IOTA WITH PSILI AND PERISPOMENI
        {U'Ἷ', U'ἷ'}, // GREEK CAPITAL LETTER IOTA WITH DASIA AND PERISPOMENI / GREEK SMALL LETTER IOTA WITH DASIA AND PERISPOMENI
        {U'Ὀ', U'ὀ'}, // GREEK CAPITAL LETTER OMICRON WITH PSILI / GREEK SMALL LETTER OMICRON WITH PSILI
        {U'Ὁ', U'ὁ'}, // GREEK CAPITAL LETTER OMICRON WITH DASIA / GREEK SMALL LETTER OMICRON WITH DASIA
        {U'Ὂ', U'ὂ'}, // GREEK CAPITAL LETTER OMICRON WITH PSILI AND VARIA / GREEK SMALL LETTER OMICRON WITH PSILI AND VARIA
        {U'Ὃ', U'ὃ'}, // GREEK CAPITAL LETTER OMICRON WITH DASIA AND VARIA / GREEK SMALL LETTER OMICRON WITH DASIA AND VARIA
        {U'Ὄ', U'ὄ'}, // GREEK CAPITAL LETTER OMICRON WITH PSILI AND OXIA / GREEK SMALL LETTER OMICRON WITH PSILI AND OXIA
        {U'Ὅ', U'ὅ'}, // GREEK CAPITAL LETTER OMICRON WITH DASIA AND OXIA / GREEK SMALL LETTER OMICRON WITH DASIA AND OXIA
        {U'Ὑ', U'ὑ'}, // GREEK CAPITAL LETTER UPSILON WITH DASIA / GREEK SMALL LETTER UPSILON WITH DASIA
        {U'Ὓ', U'ὓ'}, // GREEK CAPITAL LETTER UPSILON WITH DASIA AND VARIA / GREEK SMALL LETTER UPSILON WITH DASIA AND VARIA
        {U'Ὕ', U'ὕ'}, // GREEK CAPITAL LETTER UPSILON WITH DASIA AND OXIA / GREEK SMALL LETTER UPSILON WITH DASIA AND OXIA
        {U'Ὗ', U'ὗ'}, // GREEK CAPITAL LETTER UPSILON WITH DASIA AND PERISPOMENI / GREEK SMALL LETTER UPSILON WITH DASIA AND PERISPOMENI
        {U'Ὠ', U'ὠ'}, // GREEK CAPITAL LETTER OMEGA WITH PSILI / GREEK SMALL LETTER OMEGA WITH PSILI
        {U'Ὡ', U'ὡ'}, // GREEK CAPITAL LETTER OMEGA WITH DASIA / GREEK SMALL LETTER OMEGA WITH DASIA
        {U'Ὢ', U'ὢ'}, // GREEK CAPITAL LETTER OMEGA WITH PSILI AND VARIA / GREEK SMALL LETTER OMEGA WITH PSILI AND VARIA
        {U'Ὣ', U'ὣ'}, // GREEK CAPITAL LETTER OMEGA WITH DASIA AND VARIA / GREEK SMALL LETTER OMEGA WITH DASIA AND VARIA
        {U'Ὤ', U'ὤ'}, // GREEK CAPITAL LETTER OMEGA WITH PSILI AND OXIA / GREEK SMALL LETTER OMEGA WITH PSILI AND OXIA
        {U'Ὥ', U'ὥ'}, // GREEK CAPITAL LETTER OMEGA WITH DASIA AND OXIA / GREEK SMALL LETTER OMEGA WITH DASIA AND OXIA
        {U'Ὦ', U'ὦ'}, // GREEK CAPITAL LETTER OMEGA WITH PSILI AND PERISPOMENI / GREEK SMALL LETTER OMEGA WITH PSILI AND PERISPOMENI
        {U'Ὧ', U'ὧ'}, // GREEK CAPITAL LETTER OMEGA WITH DASIA AND PERISPOMENI / GREEK SMALL LETTER OMEGA WITH DASIA AND PERISPOMENI
        {U'ᾈ', U'ᾀ'}, // GREEK CAPITAL LETTER ALPHA WITH PSILI AND PROSGEGRAMMENI / GREEK SMALL LETTER ALPHA WITH PSILI AND YPOGEGRAMMENI
        {U'ᾉ', U'ᾁ'}, // GREEK CAPITAL LETTER ALPHA WITH DASIA AND PROSGEGRAMMENI / GREEK SMALL LETTER ALPHA WITH DASIA AND YPOGEGRAMMENI
        {U'ᾊ', U'ᾂ'}, // GREEK CAPITAL LETTER ALPHA WITH PSILI AND VARIA AND PROSGEGRAMMENI / GREEK SMALL LETTER ALPHA WITH PSILI AND VARIA AND YPOGEGRAMMENI
        {U'ᾋ', U'ᾃ'}, // GREEK CAPITAL LETTER ALPHA WITH DASIA AND VARIA AND PROSGEGRAMMENI / GREEK SMALL LETTER ALPHA WITH DASIA AND VARIA AND YPOGEGRAMMENI
        {U'ᾌ', U'ᾄ'}, // GREEK CAPITAL LETTER ALPHA WITH PSILI AND OXIA AND PROSGEGRAMMENI / GREEK SMALL LETTER ALPHA WITH PSILI AND OXIA AND YPOGEGRAMMENI
        {U'ᾍ', U'ᾅ'}, // GREEK CAPITAL LETTER ALPHA WITH DASIA AND OXIA AND PROSGEGRAMMENI / GREEK SMALL LETTER ALPHA WITH DASIA AND OXIA AND YPOGEGRAMMENI
        {U'ᾎ', U'ᾆ'}, // GREEK CAPITAL LETTER ALPHA WITH PSILI AND PERISPOMENI AND PROSGEGRAMMENI / GREEK SMALL LETTER ALPHA WITH PSILI AND PERISPOMENI AND YPOGEGRAMMENI
        {U'ᾏ', U'ᾇ'}, // GREEK CAPITAL LETTER ALPHA WITH DASIA AND PERISPOMENI AND PROSGEGRAMMENI / GREEK SMALL LETTER ALPHA WITH DASIA AND PERISPOMENI AND YPOGEGRAMMENI
        {U'ᾘ', U'ᾐ'}, // GREEK CAPITAL LETTER ETA WITH PSILI AND PROSGEGRAMMENI / GREEK SMALL LETTER ETA WITH PSILI AND YPOGEGRAMMENI
        {U'ᾙ', U'ᾑ'}, // GREEK CAPITAL LETTER ETA WITH DASIA AND PROSGEGRAMMENI / GREEK SMALL LETTER ETA WITH DASIA AND YPOGEGRAMMENI
        {U'ᾚ', U'ᾒ'}, // GREEK CAPITAL LETTER ETA WITH PSILI AND VARIA AND PROSGEGRAMMENI / GREEK SMALL LETTER ETA WITH PSILI AND VARIA AND YPOGEGRAMMENI
        {U'ᾛ', U'ᾓ'}, // GREEK CAPITAL LETTER ETA WITH DASIA AND VARIA AND PROSGEGRAMMENI / GREEK SMALL LETTER ETA WITH DASIA AND VARIA AND YPOGEGRAMMENI
        {U'ᾜ', U'ᾔ'}, // GREEK CAPITAL LETTER ETA WITH PSILI AND OXIA AND PROSGEGRAMMENI / GREEK SMALL LETTER ETA WITH PSILI AND OXIA AND YPOGEGRAMMENI
        {U'ᾝ', U'ᾕ'}, // GREEK CAPITAL LETTER ETA WITH DASIA AND OXIA AND PROSGEGRAMMENI / GREEK SMALL LETTER ETA WITH DASIA AND OXIA AND YPOGEGRAMMENI
        {U'ᾞ', U'ᾖ'}, // GREEK CAPITAL LETTER ETA WITH PSILI AND PERISPOMENI AND PROSGEGRAMMENI / GREEK SMALL LETTER ETA WITH PSILI AND PERISPOMENI AND YPOGEGRAMMENI
        {U'ᾟ', U'ᾗ'}, // GREEK CAPITAL LETTER ETA WITH DASIA AND PERISPOMENI AND PROSGEGRAMMENI / GREEK SMALL LETTER ETA WITH DASIA AND PERISPOMENI AND YPOGEGRAMMENI
        {U'ᾨ', U'ᾠ'}, // GREEK CAPITAL LETTER OMEGA WITH PSILI AND PROSGEGRAMMENI / GREEK SMALL LETTER OMEGA WITH PSILI AND YPOGEGRAMMENI
        {U'ᾩ', U'ᾡ'}, // GREEK CAPITAL LETTER OMEGA WITH DASIA AND PROSGEGRAMMENI / GREEK SMALL LETTER OMEGA WITH DASIA AND YPOGEGRAMMENI
        {U'ᾪ', U'ᾢ'}, // GREEK CAPITAL LETTER OMEGA WITH PSILI AND VARIA AND PROSGEGRAMMENI / GREEK SMALL LETTER OMEGA WITH PSILI AND VARIA AND YPOGEGRAMMENI
        {U'ᾫ', U'ᾣ'}, // GREEK CAPITAL LETTER OMEGA WITH DASIA AND VARIA AND PROSGEGRAMMENI / GREEK SMALL LETTER OMEGA WITH DASIA AND VARIA AND YPOGEGRAMMENI
        {U'ᾬ', U'ᾤ'}, // GREEK CAPITAL LETTER OMEGA WITH PSILI AND OXIA AND PROSGEGRAMMENI / GREEK SMALL LETTER OMEGA WITH PSILI AND OXIA AND YPOGEGRAMMENI
        {U'ᾭ', U'ᾥ'}, // GREEK CAPITAL LETTER OMEGA WITH DASIA AND OXIA AND PROSGEGRAMMENI / GREEK SMALL LETTER OMEGA WITH DASIA AND OXIA AND YPOGEGRAMMENI
        {U'ᾮ', U'ᾦ'}, // GREEK CAPITAL LETTER OMEGA WITH PSILI AND PERISPOMENI AND PROSGEGRAMMENI / GREEK SMALL LETTER OMEGA WITH PSILI AND PERISPOMENI AND YPOGEGRAMMENI
        {U'ᾯ', U'ᾧ'}, // GREEK CAPITAL LETTER OMEGA WITH DASIA AND PERISPOMENI AND PROSGEGRAMMENI / GREEK SMALL LETTER OMEGA WITH DASIA AND PERISPOMENI AND YPOGEGRAMMENI
        {U'Ᾰ', U'ᾰ'}, // GREEK CAPITAL LETTER ALPHA WITH VRACHY / GREEK SMALL LETTER ALPHA WITH VRACHY
        {U'Ᾱ', U'ᾱ'}, // GREEK CAPITAL LETTER ALPHA WITH MACRON / GREEK SMALL LETTER ALPHA WITH MACRON
        {U'Ὰ', U'ὰ'}, // GREEK CAPITAL LETTER ALPHA WITH VARIA / GREEK SMALL LETTER ALPHA WITH VARIA
        {U'Ά', U'ά'}, // GREEK CAPITAL LETTER ALPHA WITH OXIA / GREEK SMALL LETTER ALPHA WITH OXIA
        {U'ᾼ', U'ᾳ'}, // GREEK CAPITAL LETTER ALPHA WITH PROSGEGRAMMENI / GREEK SMALL LETTER ALPHA WITH YPOGEGRAMMENI
        {U'Ὲ', U'ὲ'}, // GREEK CAPITAL LETTER EPSILON WITH VARIA / GREEK SMALL LETTER EPSILON WITH VARIA
        {U'Έ', U'έ'}, // GREEK CAPITAL LETTER EPSILON WITH OXIA / GREEK SMALL LETTER EPSILON WITH OXIA
        {U'Ὴ', U'ὴ'}, // GREEK CAPITAL LETTER ETA WITH VARIA / GREEK SMALL LETTER ETA WITH VARIA
        {U'Ή', U'ή'}, // GREEK CAPITAL LETTER ETA WITH OXIA / GREEK SMALL LETTER ETA WITH OXIA
        {U'ῌ', U'ῃ'}, // GREEK CAPITAL LETTER ETA WITH PROSGEGRAMMENI / GREEK SMALL LETTER ETA WITH YPOGEGRAMMENI
        {U'Ῐ', U'ῐ'}, // GREEK CAPITAL LETTER IOTA WITH VRACHY / GREEK SMALL LETTER IOTA WITH VRACHY
        {U'Ῑ', U'ῑ'}, // GREEK CAPITAL LETTER IOTA WITH MACRON / GREEK SMALL LETTER IOTA WITH MACRON
        {U'Ὶ', U'ὶ'}, // GREEK CAPITAL LETTER IOTA WITH VARIA / GREEK SMALL LETTER IOTA WITH VARIA
        {U'Ί', U'ί'}, // GREEK CAPITAL LETTER IOTA WITH OXIA / GREEK SMALL LETTER IOTA WITH OXIA
        {U'Ῠ', U'ῠ'}, // GREEK CAPITAL LETTER UPSILON WITH VRACHY / GREEK SMALL LETTER UPSILON WITH VRACHY
        {U'Ῡ', U'ῡ'}, // GREEK CAPITAL LETTER UPSILON WITH MACRON / GREEK SMALL LETTER UPSILON WITH MACRON
        {U'Ὺ', U'ὺ'}, // GREEK CAPITAL LETTER UPSILON WITH VARIA / GREEK SMALL LETTER UPSILON WITH VARIA
        {U'Ύ', U'ύ'}, // GREEK CAPITAL LETTER UPSILON WITH OXIA / GREEK SMALL LETTER UPSILON WITH OXIA
        {U'Ῥ', U'ῥ'}, // GREEK CAPITAL LETTER RHO WITH DASIA / GREEK SMALL LETTER RHO WITH DASIA
        {U'Ὸ', U'ὸ'}, // GREEK CAPITAL LETTER OMICRON WITH VARIA / GREEK SMALL LETTER OMICRON WITH VARIA
        {U'Ό', U'ό'}, // GREEK CAPITAL LETTER OMICRON WITH OXIA / GREEK SMALL LETTER OMICRON WITH OXIA
        {U'Ὼ', U'ὼ'}, // GREEK CAPITAL LETTER OMEGA WITH VARIA / GREEK SMALL LETTER OMEGA WITH VARIA
        {U'Ώ', U'ώ'}, // GREEK CAPITAL LETTER OMEGA WITH OXIA / GREEK SMALL LETTER OMEGA WITH OXIA
        {U'ῼ', U'ῳ'}, // GREEK CAPITAL LETTER OMEGA WITH PROSGEGRAMMENI / GREEK SMALL LETTER OMEGA WITH YPOGEGRAMMENI
        {U'Ω', U'ω'}, // OHM SIGN / GREEK SMALL LETTER OMEGA
        {U'K', U'k'}, // KELVIN SIGN / LATIN SMALL LETTER K
        {U'Å', U'å'}, // ANGSTROM SIGN / LATIN SMALL LETTER A WITH RING ABOVE
        {U'Ⅎ', U'ⅎ'}, // TURNED CAPITAL F / TURNED SMALL F
        {U'Ⅰ', U'ⅰ'}, // ROMAN NUMERAL ONE / SMALL ROMAN NUMERAL ONE
        {U'Ⅱ', U'ⅱ'}, // ROMAN NUMERAL TWO / SMALL ROMAN NUMERAL TWO
        {U'Ⅲ', U'ⅲ'}, // ROMAN NUMERAL THREE / SMALL ROMAN NUMERAL THREE
        {U'Ⅳ', U'ⅳ'}, // ROMAN NUMERAL FOUR / SMALL ROMAN NUMERAL FOUR
        {U'Ⅴ', U'ⅴ'}, // ROMAN NUMERAL FIVE / SMALL ROMAN NUMERAL FIVE
        {U'Ⅵ', U'ⅵ'}, // ROMAN NUMERAL SIX / SMALL ROMAN NUMERAL SIX
        {U'Ⅶ', U'ⅶ'}, // ROMAN NUMERAL SEVEN / SMALL ROMAN NUMERAL SEVEN
        {U'Ⅷ', U'ⅷ'}, // ROMAN NUMERAL EIGHT / SMALL ROMAN NUMERAL EIGHT
        {U'Ⅸ', U'ⅸ'}, // ROMAN NUMERAL NINE / SMALL ROMAN NUMERAL NINE
        {U'Ⅹ', U'ⅹ'}, // ROMAN NUMERAL TEN / SMALL ROMAN NUMERAL TEN
        {U'Ⅺ', U'ⅺ'}, // ROMAN NUMERAL ELEVEN / SMALL ROMAN NUMERAL ELEVEN
        {U'Ⅻ', U'ⅻ'}, // ROMAN NUMERAL TWELVE / SMALL ROMAN NUMERAL TWELVE
        {U'Ⅼ', U'ⅼ'}, // ROMAN NUMERAL FIFTY / SMALL ROMAN NUMERAL FIFTY
        {U'Ⅽ', U'ⅽ'}, // ROMAN NUMERAL ONE HUNDRED / SMALL ROMAN NUMERAL ONE HUNDRED
        {U'Ⅾ', U'ⅾ'}, // ROMAN NUMERAL FIVE HUNDRED / SMALL ROMAN NUMERAL FIVE HUNDRED
        {U'Ⅿ', U'ⅿ'}, // ROMAN NUMERAL ONE THOUSAND / SMALL ROMAN NUMERAL ONE THOUSAND
        {U'Ↄ', U'ↄ'}, // ROMAN NUMERAL REVERSED ONE HUNDRED / LATIN SMALL LETTER REVERSED C
        {U'Ⓐ', U'ⓐ'}, // CIRCLED LATIN CAPITAL LETTER A / CIRCLED LATIN SMALL LETTER A
        {U'Ⓑ', U'ⓑ'}, // CIRCLED LATIN CAPITAL LETTER B / CIRCLED LATIN SMALL LETTER B
        {U'Ⓒ', U'ⓒ'}, // CIRCLED LATIN CAPITAL LETTER C / CIRCLED LATIN SMALL LETTER C
        {U'Ⓓ', U'ⓓ'}, // CIRCLED LATIN CAPITAL LETTER D / CIRCLED LATIN SMALL LETTER D
        {U'Ⓔ', U'ⓔ'}, // CIRCLED LATIN CAPITAL LETTER E / CIRCLED LATIN SMALL LETTER E
        {U'Ⓕ', U'ⓕ'}, // CIRCLED LATIN CAPITAL LETTER F / CIRCLED LATIN SMALL LETTER F
        {U'Ⓖ', U'ⓖ'}, // CIRCLED LATIN CAPITAL LETTER G / CIRCLED LATIN SMALL LETTER G
        {U'Ⓗ', U'ⓗ'}, // CIRCLED LATIN CAPITAL LETTER H / CIRCLED LATIN SMALL LETTER H
        {U'Ⓘ', U'ⓘ'}, // CIRCLED LATIN CAPITAL LETTER I / CIRCLED LATIN SMALL LETTER I
        {U'Ⓙ', U'ⓙ'}, // CIRCLED LATIN CAPITAL LETTER J / CIRCLED LATIN SMALL LETTER J
        {U'Ⓚ', U'ⓚ'}, // CIRCLED LATIN CAPITAL LETTER K / CIRCLED LATIN SMALL LETTER K
        {U'Ⓛ', U'ⓛ'}, // CIRCLED LATIN CAPITAL LETTER L / CIRCLED LATIN SMALL LETTER L
        {U'Ⓜ', U'ⓜ'}, // CIRCLED LATIN CAPITAL LETTER M / CIRCLED LATIN SMALL LETTER M
        {U'Ⓝ', U'ⓝ'}, // CIRCLED LATIN CAPITAL LETTER N / CIRCLED LATIN SMALL LETTER N
        {U'Ⓞ', U'ⓞ'}, // CIRCLED LATIN CAPITAL LETTER O / CIRCLED LATIN SMALL LETTER O
        {U'Ⓟ', U'ⓟ'}, // CIRCLED LATIN CAPITAL LETTER P / CIRCLED LATIN SMALL LETTER P
        {U'Ⓠ', U'ⓠ'}, // CIRCLED LATIN CAPITAL LETTER Q / CIRCLED LATIN SMALL LETTER Q
        {U'Ⓡ', U'ⓡ'}, // CIRCLED LATIN CAPITAL LETTER R / CIRCLED LATIN SMALL LETTER R
        {U'Ⓢ', U'ⓢ'}, // CIRCLED LATIN CAPITAL LETTER S / CIRCLED LATIN SMALL LETTER S
        {U'Ⓣ', U'ⓣ'}, // CIRCLED LATIN CAPITAL LETTER T / CIRCLED LATIN SMALL LETTER T
        {U'Ⓤ', U'ⓤ'}, // CIRCLED LATIN CAPITAL LETTER U / CIRCLED LATIN SMALL LETTER U
        {U'Ⓥ', U'ⓥ'}, // CIRCLED LATIN CAPITAL LETTER V / CIRCLED LATIN SMALL LETTER V
        {U'Ⓦ', U'ⓦ'}, // CIRCLED LATIN CAPITAL LETTER W / CIRCLED LATIN SMALL LETTER W
        {U'Ⓧ', U'ⓧ'}, // CIRCLED LATIN CAPITAL LETTER X / CIRCLED LATIN SMALL LETTER X
        {U'Ⓨ', U'ⓨ'}, // CIRCLED LATIN CAPITAL LETTER Y / CIRCLED LATIN SMALL LETTER Y
        {U'Ⓩ', U'ⓩ'}, // CIRCLED LATIN CAPITAL LETTER Z / CIRCLED LATIN SMALL LETTER Z
        {U'Ⰰ', U'ⰰ'}, // GLAGOLITIC CAPITAL LETTER AZU / GLAGOLITIC SMALL LETTER AZU
        {U'Ⰱ', U'ⰱ'}, // GLAGOLITIC CAPITAL LETTER BUKY / GLAGOLITIC SMALL LETTER BUKY
        {U'Ⰲ', U'ⰲ'}, // GLAGOLITIC CAPITAL LETTER VEDE / GLAGOLITIC SMALL LETTER VEDE
        {U'Ⰳ', U'ⰳ'}, // GLAGOLITIC CAPITAL LETTER GLAGOLI / GLAGOLITIC SMALL LETTER GLAGOLI
        {U'Ⰴ', U'ⰴ'}, // GLAGOLITIC CAPITAL LETTER DOBRO / GLAGOLITIC SMALL LETTER DOBRO
        {U'Ⰵ', U'ⰵ'}, // GLAGOLITIC CAPITAL LETTER YESTU / GLAGOLITIC SMALL LETTER YESTU
        {U'Ⰶ', U'ⰶ'}, // GLAGOLITIC CAPITAL LETTER ZHIVETE / GLAGOLITIC SMALL LETTER ZHIVETE
        {U'Ⰷ', U'ⰷ'}, // GLAGOLITIC CAPITAL LETTER DZELO / GLAGOLITIC SMALL LETTER DZELO
        {U'Ⰸ', U'ⰸ'}, // GLAGOLITIC CAPITAL LETTER ZEMLJA / GLAGOLITIC SMALL LETTER ZEMLJA
        {U'Ⰹ', U'ⰹ'}, // GLAGOLITIC CAPITAL LETTER IZHE / GLAGOLITIC SMALL LETTER IZHE
        {U'Ⰺ', U'ⰺ'}, // GLAGOLITIC CAPITAL LETTER INITIAL IZHE / GLAGOLITIC SMALL LETTER INITIAL IZHE
        {U'Ⰻ', U'ⰻ'}, // GLAGOLITIC CAPITAL LETTER I / GLAGOLITIC SMALL LETTER I
        {U'Ⰼ', U'ⰼ'}, // GLAGOLITIC CAPITAL LETTER DJERVI / GLAGOLITIC SMALL LETTER DJERVI
        {U'Ⰽ', U'ⰽ'}, // GLAGOLITIC CAPITAL LETTER KAKO / GLAGOLITIC SMALL LETTER KAKO
        {U'Ⰾ', U'ⰾ'}, // GLAGOLITIC CAPITAL LETTER LJUDIJE / GLAGOLITIC SMALL LETTER LJUDIJE
        {U'Ⰿ', U'ⰿ'}, // GLAGOLITIC CAPITAL LETTER MYSLITE / GLAGOLITIC SMALL LETTER MYSLITE
        {U'Ⱀ', U'ⱀ'}, // GLAGOLITIC CAPITAL LETTER NASHI / GLAGOLITIC SMALL LETTER NASHI
        {U'Ⱁ', U'ⱁ'}, // GLAGOLITIC CAPITAL LETTER ONU / GLAGOLITIC SMALL LETTER ONU
        {U'Ⱂ', U'ⱂ'}, // GLAGOLITIC CAPITAL LETTER POKOJI / GLAGOLITIC SMALL LETTER POKOJI
        {U'Ⱃ', U'ⱃ'}, // GLAGOLITIC CAPITAL LETTER RITSI / GLAGOLITIC SMALL LETTER RITSI
        {U'Ⱄ', U'ⱄ'}, // GLAGOLITIC CAPITAL LETTER SLOVO / GLAGOLITIC SMALL LETTER SLOVO
        {U'Ⱅ', U'ⱅ'}, // GLAGOLITIC CAPITAL LETTER TVRIDO / GLAGOLITIC SMALL LETTER TVRIDO
        {U'Ⱆ', U'ⱆ'}, // GLAGOLITIC CAPITAL LETTER UKU / GLAGOLITIC SMALL LETTER UKU
        {U'Ⱇ', U'ⱇ'}, // GLAGOLITIC CAPITAL LETTER FRITU / GLAGOLITIC SMALL LETTER FRITU
        {U'Ⱈ', U'ⱈ'}, // GLAGOLITIC CAPITAL LETTER HERU / GLAGOLITIC SMALL LETTER HERU
        {U'Ⱉ', U'ⱉ'}, // GLAGOLITIC CAPITAL LETTER OTU / GLAGOLITIC SMALL LETTER OTU
        {U'Ⱊ', U'ⱊ'}, // GLAGOLITIC CAPITAL LETTER PE / GLAGOLITIC SMALL LETTER PE
        {U'Ⱋ', U'ⱋ'}, // GLAGOLITIC CAPITAL LETTER SHTA / GLAGOLITIC SMALL LETTER SHTA
        {U'Ⱌ', U'ⱌ'}, // GLAGOLITIC CAPITAL LETTER TSI / GLAGOLITIC SMALL LETTER TSI
        {U'Ⱍ', U'ⱍ'}, // GLAGOLITIC CAPITAL LETTER CHRIVI / GLAGOLITIC SMALL LETTER CHRIVI
        {U'Ⱎ', U'ⱎ'}, // GLAGOLITIC CAPITAL LETTER SHA / GLAGOLITIC SMALL LETTER SHA
        {U'Ⱏ', U'ⱏ'}, // GLAGOLITIC CAPITAL LETTER YERU / GLAGOLITIC SMALL LETTER YERU
        {U'Ⱐ', U'ⱐ'}, // GLAGOLITIC CAPITAL LETTER YERI / GLAGOLITIC SMALL LETTER YERI
        {U'Ⱑ', U'ⱑ'}, // GLAGOLITIC CAPITAL LETTER YATI / GLAGOLITIC SMALL LETTER YATI
        {U'Ⱒ', U'ⱒ'}, // GLAGOLITIC CAPITAL LETTER SPIDERY HA / GLAGOLITIC SMALL LETTER SPIDERY HA
        {U'Ⱓ', U'ⱓ'}, // GLAGOLITIC CAPITAL LETTER YU / GLAGOLITIC SMALL LETTER YU
        {U'Ⱔ', U'ⱔ'}, // GLAGOLITIC CAPITAL LETTER SMALL YUS / GLAGOLITIC SMALL LETTER SMALL YUS
        {U'Ⱕ', U'ⱕ'}, // GLAGOLITIC CAPITAL LETTER SMALL YUS WITH TAIL / GLAGOLITIC SMALL LETTER SMALL YUS WITH TAIL
        {U'Ⱖ', U'ⱖ'}, // GLAGOLITIC CAPITAL LETTER YO / GLAGOLITIC SMALL LETTER YO
        {U'Ⱗ', U'ⱗ'}, // GLAGOLITIC CAPITAL LETTER IOTATED SMALL YUS / GLAGOLITIC SMALL LETTER IOTATED SMALL YUS
        {U'Ⱘ', U'ⱘ'}, // GLAGOLITIC CAPITAL LETTER BIG YUS / GLAGOLITIC SMALL LETTER BIG YUS
        {U'Ⱙ', U'ⱙ'}, // GLAGOLITIC CAPITAL LETTER IOTATED BIG YUS / GLAGOLITIC SMALL LETTER IOTATED BIG YUS
        {U'Ⱚ', U'ⱚ'}, // GLAGOLITIC CAPITAL LETTER FITA / GLAGOLITIC SMALL LETTER FITA
        {U'Ⱛ', U'ⱛ'}, // GLAGOLITIC CAPITAL LETTER IZHITSA / GLAGOLITIC SMALL LETTER IZHITSA
        {U'Ⱜ', U'ⱜ'}, // GLAGOLITIC CAPITAL LETTER SHTAPIC / GLAGOLITIC SMALL LETTER SHTAPIC
        {U'Ⱝ', U'ⱝ'}, // GLAGOLITIC CAPITAL LETTER TROKUTASTI A / GLAGOLITIC SMALL LETTER TROKUTASTI A
        {U'Ⱞ', U'ⱞ'}, // GLAGOLITIC CAPITAL LETTER LATINATE MYSLITE / GLAGOLITIC SMALL LETTER LATINATE MYSLITE
        {U'Ⱡ', U'ⱡ'}, // LATIN CAPITAL LETTER L WITH DOUBLE BAR / LATIN SMALL LETTER L WITH DOUBLE BAR
        {U'Ɫ', U'ɫ'}, // LATIN CAPITAL LETTER L WITH MIDDLE TILDE / LATIN SMALL LETTER L WITH MIDDLE TILDE
        {U'Ᵽ', U'ᵽ'}, // LATIN CAPITAL LETTER P WITH STROKE / LATIN SMALL LETTER P WITH STROKE
        {U'Ɽ', U'ɽ'}, // LATIN CAPITAL LETTER R WITH TAIL / LATIN SMALL LETTER R WITH TAIL
        {U'Ⱨ', U'ⱨ'}, // LATIN CAPITAL LETTER H WITH DESCENDER / LATIN SMALL LETTER H WITH DESCENDER
        {U'Ⱪ', U'ⱪ'}, // LATIN CAPITAL LETTER K WITH DESCENDER / LATIN SMALL LETTER K WITH DESCENDER
        {U'Ⱬ', U'ⱬ'}, // LATIN CAPITAL LETTER Z WITH DESCENDER / LATIN SMALL LETTER Z WITH DESCENDER
        {U'Ɑ', U'ɑ'}, // LATIN CAPITAL LETTER ALPHA / LATIN SMALL LETTER ALPHA
        {U'Ɱ', U'ɱ'}, // LATIN CAPITAL LETTER M WITH HOOK / LATIN SMALL LETTER M WITH HOOK
        {U'Ɐ', U'ɐ'}, // LATIN CAPITAL LETTER TURNED A / LATIN SMALL LETTER TURNED A
        {U'Ɒ', U'ɒ'}, // LATIN CAPITAL LETTER TURNED ALPHA / LATIN SMALL LETTER TURNED ALPHA
        {U'Ⱳ', U'ⱳ'}, // LATIN CAPITAL LETTER W WITH HOOK / LATIN SMALL LETTER W WITH HOOK
        {U'Ⱶ', U'ⱶ'}, // LATIN CAPITAL LETTER HALF H / LATIN SMALL LETTER HALF H
        {U'Ȿ', U'ȿ'}, // LATIN CAPITAL LETTER S WITH SWASH TAIL / LATIN SMALL LETTER S WITH SWASH TAIL
        {U'Ɀ', U'ɀ'}, // LATIN CAPITAL LETTER Z WITH SWASH TAIL / LATIN SMALL LETTER Z WITH SWASH TAIL
        {U'Ⲁ', U'ⲁ'}, // COPTIC CAPITAL LETTER ALFA / COPTIC SMALL LETTER ALFA
        {U'Ⲃ', U'ⲃ'}, // COPTIC CAPITAL LETTER VIDA / COPTIC SMALL LETTER VIDA
        {U'Ⲅ', U'ⲅ'}, // COPTIC CAPITAL LETTER GAMMA / COPTIC SMALL LETTER GAMMA
        {U'Ⲇ', U'ⲇ'}, // COPTIC CAPITAL LETTER DALDA / COPTIC SMALL LETTER DALDA
        {U'Ⲉ', U'ⲉ'}, // COPTIC CAPITAL LETTER EIE / COPTIC SMALL LETTER EIE
        {U'Ⲋ', U'ⲋ'}, // COPTIC CAPITAL LETTER SOU / COPTIC SMALL LETTER SOU
        {U'Ⲍ', U'ⲍ'}, // COPTIC CAPITAL LETTER ZATA / COPTIC SMALL LETTER ZATA
        {U'Ⲏ', U'ⲏ'}, // COPTIC CAPITAL LETTER HATE / COPTIC SMALL LETTER HATE
        {U'Ⲑ', U'ⲑ'}, // COPTIC CAPITAL LETTER THETHE / COPTIC SMALL LETTER THETHE
        {U'Ⲓ', U'ⲓ'}, // COPTIC CAPITAL LETTER IAUDA / COPTIC SMALL LETTER IAUDA
        {U'Ⲕ', U'ⲕ'}, // COPTIC CAPITAL LETTER KAPA / COPTIC SMALL LETTER KAPA
        {U'Ⲗ', U'ⲗ'}, // COPTIC CAPITAL LETTER LAULA / COPTIC SMALL LETTER LAULA
        {U'Ⲙ', U'ⲙ'}, // COPTIC CAPITAL LETTER MI / COPTIC SMALL LETTER MI
        {U'Ⲛ', U'ⲛ'}, // COPTIC CAPITAL LETTER NI / COPTIC SMALL LETTER NI
        {U'Ⲝ', U'ⲝ'}, // COPTIC CAPITAL LETTER KSI / COPTIC SMALL LETTER KSI
        {U'Ⲟ', U'ⲟ'}, // COPTIC CAPITAL LETTER O / COPTIC SMALL LETTER O
        {U'Ⲡ', U'ⲡ'}, // COPTIC CAPITAL LETTER PI / COPTIC SMALL LETTER PI
        {U'Ⲣ', U'ⲣ'}, // COPTIC CAPITAL LETTER RO / COPTIC SMALL LETTER RO
        {U'Ⲥ', U'ⲥ'}, // COPTIC CAPITAL LETTER SIMA / COPTIC SMALL LETTER SIMA
        {U'Ⲧ', U'ⲧ'}, // COPTIC CAPITAL LETTER TAU / COPTIC SMALL LETTER TAU
        {U'Ⲩ', U'ⲩ'}, // COPTIC CAPITAL LETTER UA / COPTIC SMALL LETTER UA
        {U'Ⲫ', U'ⲫ'}, // COPTIC CAPITAL LETTER FI / COPTIC SMALL LETTER FI
        {U'Ⲭ', U'ⲭ'}, // COPTIC CAPITAL LETTER KHI / COPTIC SMALL LETTER KHI
        {U'Ⲯ', U'ⲯ'}, // COPTIC CAPITAL LETTER PSI / COPTIC SMALL LETTER PSI
        {U'Ⲱ', U'ⲱ'}, // COPTIC CAPITAL LETTER OOU / COPTIC SMALL LETTER OOU
        {U'Ⲳ', U'ⲳ'}, // COPTIC CAPITAL LETTER DIALECT-P ALEF / COPTIC SMALL LETTER DIALECT-P ALEF
        {U'Ⲵ', U'ⲵ'}, // COPTIC CAPITAL LETTER OLD COPTIC AIN / COPTIC SMALL LETTER OLD COPTIC AIN
        {U'Ⲷ', U'ⲷ'}, // COPTIC CAPITAL LETTER CRYPTOGRAMMIC EIE / COPTIC SMALL LETTER CRYPTOGRAMMIC EIE
        {U'Ⲹ', U'ⲹ'}, // COPTIC CAPITAL LETTER DIALECT-P KAPA / COPTIC SMALL LETTER DIALECT-P KAPA
        {U'Ⲻ', U'ⲻ'}, // COPTIC CAPITAL LETTER DIALECT-P NI / COPTIC SMALL LETTER DIALECT-P NI
        {U'Ⲽ', U'ⲽ'}, // COPTIC CAPITAL LETTER CRYPTOGRAMMIC NI / COPTIC SMALL LETTER CRYPTOGRAMMIC NI
        {U'Ⲿ', U'ⲿ'}, // COPTIC CAPITAL LETTER OLD COPTIC OOU / COPTIC SMALL LETTER OLD COPTIC OOU
        {U'Ⳁ', U'ⳁ'}, // COPTIC CAPITAL LETTER SAMPI / COPTIC SMALL LETTER SAMPI
        {U'Ⳃ', U'ⳃ'}, // COPTIC CAPITAL LETTER CROSSED SHEI / COPTIC SMALL LETTER CROSSED SHEI
        {U'Ⳅ', U'ⳅ'}, // COPTIC CAPITAL LETTER OLD COPTIC SHEI / COPTIC SMALL LETTER OLD COPTIC SHEI
        {U'Ⳇ', U'ⳇ'}, // COPTIC CAPITAL LETTER OLD COPTIC ESH / COPTIC SMALL LETTER OLD COPTIC ESH
        {U'Ⳉ', U'ⳉ'}, // COPTIC CAPITAL LETTER AKHMIMIC KHEI / COPTIC SMALL LETTER AKHMIMIC KHEI
        {U'Ⳋ', U'ⳋ'}, // COPTIC CAPITAL LETTER DIALECT-P HORI / COPTIC SMALL LETTER DIALECT-P HORI
        {U'Ⳍ', U'ⳍ'}, // COPTIC CAPITAL LETTER OLD COPTIC HORI / COPTIC SMALL LETTER OLD COPTIC HORI
        {U'Ⳏ', U'ⳏ'}, // COPTIC CAPITAL LETTER OLD COPTIC HA / COPTIC SMALL LETTER OLD COPTIC HA
        {U'Ⳑ', U'ⳑ'}, // COPTIC CAPITAL LETTER L-SHAPED HA / COPTIC SMALL LETTER L-SHAPED HA
        {U'Ⳓ', U'ⳓ'}, // COPTIC CAPITAL LETTER OLD COPTIC HEI / COPTIC SMALL LETTER OLD COPTIC HEI
        {U'Ⳕ', U'ⳕ'}, // COPTIC CAPITAL LETTER OLD COPTIC HAT / COPTIC SMALL LETTER OLD COPTIC HAT
        {U'Ⳗ', U'ⳗ'}, // COPTIC CAPITAL LETTER OLD COPTIC GANGIA / COPTIC SMALL LETTER OLD COPTIC GANGIA
        {U'Ⳙ', U'ⳙ'}, // COPTIC CAPITAL LETTER OLD COPTIC DJA / COPTIC SMALL LETTER OLD COPTIC DJA
        {U'Ⳛ', U'ⳛ'}, // COPTIC CAPITAL LETTER OLD COPTIC SHIMA / COPTIC SMALL LETTER OLD COPTIC SHIMA
        {U'Ⳝ', U'ⳝ'}, // COPTIC CAPITAL LETTER OLD NUBIAN SHIMA / COPTIC SMALL LETTER OLD NUBIAN SHIMA
        {U'Ⳟ', U'ⳟ'}, // COPTIC CAPITAL LETTER OLD NUBIAN NGI / COPTIC SMALL LETTER OLD NUBIAN NGI
        {U'Ⳡ', U'ⳡ'}, // COPTIC CAPITAL LETTER OLD NUBIAN NYI / COPTIC SMALL LETTER OLD NUBIAN NYI
        {U'Ⳣ', U'ⳣ'}, // COPTIC CAPITAL LETTER OLD NUBIAN WAU / COPTIC SMALL LETTER OLD NUBIAN WAU
        {U'Ⳬ', U'ⳬ'}, // COPTIC CAPITAL LETTER CRYPTOGRAMMIC SHEI / COPTIC SMALL LETTER CRYPTOGRAMMIC SHEI
        {U'Ⳮ', U'ⳮ'}, // COPTIC CAPITAL LETTER CRYPTOGRAMMIC GANGIA / COPTIC SMALL LETTER CRYPTOGRAMMIC GANGIA
        {U'Ⳳ', U'ⳳ'}, // COPTIC CAPITAL LETTER BOHAIRIC KHEI / COPTIC SMALL LETTER BOHAIRIC KHEI
        {U'Ꙁ', U'ꙁ'}, // CYRILLIC CAPITAL LETTER ZEMLYA / CYRILLIC SMALL LETTER ZEMLYA
        {U'Ꙃ', U'ꙃ'}, // CYRILLIC CAPITAL LETTER DZELO / CYRILLIC SMALL LETTER DZELO
        {U'Ꙅ', U'ꙅ'}, // CYRILLIC CAPITAL LETTER REVERSED DZE / CYRILLIC SMALL LETTER REVERSED DZE
        {U'Ꙇ', U'ꙇ'}, // CYRILLIC CAPITAL LETTER IOTA / CYRILLIC SMALL LETTER IOTA
        {U'Ꙉ', U'ꙉ'}, // CYRILLIC CAPITAL LETTER DJERV / CYRILLIC SMALL LETTER DJERV
        {U'Ꙋ', U'ꙋ'}, // CYRILLIC CAPITAL LETTER MONOGRAPH UK / CYRILLIC SMALL LETTER MONOGRAPH UK
        {U'Ꙍ', U'ꙍ'}, // CYRILLIC CAPITAL LETTER BROAD OMEGA / CYRILLIC SMALL LETTER BROAD OMEGA
        {U'Ꙏ', U'ꙏ'}, // CYRILLIC CAPITAL LETTER NEUTRAL YER / CYRILLIC SMALL LETTER NEUTRAL YER
        {U'Ꙑ', U'ꙑ'}, // CYRILLIC CAPITAL LETTER YERU WITH BACK YER / CYRILLIC SMALL LETTER YERU WITH BACK YER
        {U'Ꙓ', U'ꙓ'}, // CYRILLIC CAPITAL LETTER IOTIFIED YAT / CYRILLIC SMALL LETTER IOTIFIED YAT
        {U'Ꙕ', U'ꙕ'}, // CYRILLIC CAPITAL LETTER REVERSED YU / CYRILLIC SMALL LETTER REVERSED YU
        {U'Ꙗ', U'ꙗ'}, // CYRILLIC CAPITAL LETTER IOTIFIED A / CYRILLIC SMALL LETTER IOTIFIED A
        {U'Ꙙ', U'ꙙ'}, // CYRILLIC CAPITAL LETTER CLOSED LITTLE YUS / CYRILLIC SMALL LETTER CLOSED LITTLE YUS
        {U'Ꙛ', U'ꙛ'}, // CYRILLIC CAPITAL LETTER BLENDED YUS / CYRILLIC SMALL LETTER BLENDED YUS
        {U'Ꙝ', U'ꙝ'}, // CYRILLIC CAPITAL LETTER IOTIFIED CLOSED LITTLE YUS / CYRILLIC SMALL LETTER IOTIFIED CLOSED LITTLE YUS
        {U'Ꙟ', U'ꙟ'}, // CYRILLIC CAPITAL LETTER YN / CYRILLIC SMALL LETTER YN
    };
}
